// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: notifier.proto

package notificationstreamservice

import (
	"context"

	"github.com/og-game/game-proto/proto-gen-go/notifier/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchConfig                    = v1.BatchConfig
	BatchSendRequest               = v1.BatchSendRequest
	BatchSendResponse              = v1.BatchSendResponse
	CategoryWithEventTypes         = v1.CategoryWithEventTypes
	ConfigureEndpointInfo          = v1.ConfigureEndpointInfo
	ConfigureEndpointRequest       = v1.ConfigureEndpointRequest
	ConfigureEndpointResponse      = v1.ConfigureEndpointResponse
	CreateSubscriptionInfo         = v1.CreateSubscriptionInfo
	CreateSubscriptionRequest      = v1.CreateSubscriptionRequest
	CreateSubscriptionResponse     = v1.CreateSubscriptionResponse
	DeleteSubscriptionRequest      = v1.DeleteSubscriptionRequest
	EndpointConfig                 = v1.EndpointConfig
	EventTypeDetail                = v1.EventTypeDetail
	FilterConfig                   = v1.FilterConfig
	FilterRules                    = v1.FilterRules
	GetEventTypesData              = v1.GetEventTypesData
	GetEventTypesRequest           = v1.GetEventTypesRequest
	GetEventTypesResponse          = v1.GetEventTypesResponse
	NotificationMsgHandlerInfo     = v1.NotificationMsgHandlerInfo
	NotificationMsgHandlerRequest  = v1.NotificationMsgHandlerRequest
	NotificationMsgHandlerResponse = v1.NotificationMsgHandlerResponse
	NotifyBaseResp                 = v1.NotifyBaseResp
	PushTask                       = v1.PushTask
	QueryPushRecords               = v1.QueryPushRecords
	QueryPushRecordsRequest        = v1.QueryPushRecordsRequest
	QueryPushRecordsResponse       = v1.QueryPushRecordsResponse
	RateLimits                     = v1.RateLimits
	SendNotificationRequest        = v1.SendNotificationRequest
	SendNotificationResponse       = v1.SendNotificationResponse
	SubscriptionConfig             = v1.SubscriptionConfig
	TargetAll                      = v1.TargetAll
	TargetCategory                 = v1.TargetCategory
	TargetMerchants                = v1.TargetMerchants
	TestEndpointInfo               = v1.TestEndpointInfo
	TestEndpointRequest            = v1.TestEndpointRequest
	TestEndpointResponse           = v1.TestEndpointResponse
	UpdateSubscriptionRequest      = v1.UpdateSubscriptionRequest

	NotificationStreamService interface {
		// 双向流式通知推送
		StreamNotifications(ctx context.Context, opts ...grpc.CallOption) (v1.NotificationStreamService_StreamNotificationsClient, error)
	}

	defaultNotificationStreamService struct {
		cli zrpc.Client
	}
)

func NewNotificationStreamService(cli zrpc.Client) NotificationStreamService {
	return &defaultNotificationStreamService{
		cli: cli,
	}
}

// 双向流式通知推送
func (m *defaultNotificationStreamService) StreamNotifications(ctx context.Context, opts ...grpc.CallOption) (v1.NotificationStreamService_StreamNotificationsClient, error) {
	client := v1.NewNotificationStreamServiceClient(m.cli.Conn())
	return client.StreamNotifications(ctx, opts...)
}
