// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: temporal.proto

package workflowexecutionservice

import (
	"context"

	"github.com/og-game/game-proto/proto-gen-go/temporal/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchStartWorkflowRequest  = v1.BatchStartWorkflowRequest
	BatchStartWorkflowResponse = v1.BatchStartWorkflowResponse
	CancelWorkflowRequest      = v1.CancelWorkflowRequest
	CancelWorkflowResponse     = v1.CancelWorkflowResponse
	CreateScheduleRequest      = v1.CreateScheduleRequest
	CreateScheduleResponse     = v1.CreateScheduleResponse
	DeleteScheduleRequest      = v1.DeleteScheduleRequest
	DeleteScheduleResponse     = v1.DeleteScheduleResponse
	GetScheduleRequest         = v1.GetScheduleRequest
	GetScheduleResponse        = v1.GetScheduleResponse
	GetWorkflowHistoryRequest  = v1.GetWorkflowHistoryRequest
	GetWorkflowHistoryResponse = v1.GetWorkflowHistoryResponse
	GetWorkflowStatusRequest   = v1.GetWorkflowStatusRequest
	GetWorkflowStatusResponse  = v1.GetWorkflowStatusResponse
	ListSchedulesRequest       = v1.ListSchedulesRequest
	ListSchedulesResponse      = v1.ListSchedulesResponse
	ListWorkflowsRequest       = v1.ListWorkflowsRequest
	ListWorkflowsResponse      = v1.ListWorkflowsResponse
	PauseScheduleRequest       = v1.PauseScheduleRequest
	PauseScheduleResponse      = v1.PauseScheduleResponse
	QueryWorkflowRequest       = v1.QueryWorkflowRequest
	QueryWorkflowResponse      = v1.QueryWorkflowResponse
	ScheduleInfo               = v1.ScheduleInfo
	SignalWithStartRequest     = v1.SignalWithStartRequest
	SignalWithStartResponse    = v1.SignalWithStartResponse
	SignalWorkflowRequest      = v1.SignalWorkflowRequest
	SignalWorkflowResponse     = v1.SignalWorkflowResponse
	StartWorkflowRequest       = v1.StartWorkflowRequest
	StartWorkflowResponse      = v1.StartWorkflowResponse
	TerminateWorkflowRequest   = v1.TerminateWorkflowRequest
	TerminateWorkflowResponse  = v1.TerminateWorkflowResponse
	WorkflowEvent              = v1.WorkflowEvent
	WorkflowInfo               = v1.WorkflowInfo

	WorkflowExecutionService interface {
		// 启动工作流
		StartWorkflow(ctx context.Context, in *StartWorkflowRequest, opts ...grpc.CallOption) (*StartWorkflowResponse, error)
		// 批量启动工作流
		BatchStartWorkflow(ctx context.Context, in *BatchStartWorkflowRequest, opts ...grpc.CallOption) (*BatchStartWorkflowResponse, error)
		// 取消工作流
		CancelWorkflow(ctx context.Context, in *CancelWorkflowRequest, opts ...grpc.CallOption) (*CancelWorkflowResponse, error)
		// 终止工作流
		TerminateWorkflow(ctx context.Context, in *TerminateWorkflowRequest, opts ...grpc.CallOption) (*TerminateWorkflowResponse, error)
	}

	defaultWorkflowExecutionService struct {
		cli zrpc.Client
	}
)

func NewWorkflowExecutionService(cli zrpc.Client) WorkflowExecutionService {
	return &defaultWorkflowExecutionService{
		cli: cli,
	}
}

// 启动工作流
func (m *defaultWorkflowExecutionService) StartWorkflow(ctx context.Context, in *StartWorkflowRequest, opts ...grpc.CallOption) (*StartWorkflowResponse, error) {
	client := v1.NewWorkflowExecutionServiceClient(m.cli.Conn())
	return client.StartWorkflow(ctx, in, opts...)
}

// 批量启动工作流
func (m *defaultWorkflowExecutionService) BatchStartWorkflow(ctx context.Context, in *BatchStartWorkflowRequest, opts ...grpc.CallOption) (*BatchStartWorkflowResponse, error) {
	client := v1.NewWorkflowExecutionServiceClient(m.cli.Conn())
	return client.BatchStartWorkflow(ctx, in, opts...)
}

// 取消工作流
func (m *defaultWorkflowExecutionService) CancelWorkflow(ctx context.Context, in *CancelWorkflowRequest, opts ...grpc.CallOption) (*CancelWorkflowResponse, error) {
	client := v1.NewWorkflowExecutionServiceClient(m.cli.Conn())
	return client.CancelWorkflow(ctx, in, opts...)
}

// 终止工作流
func (m *defaultWorkflowExecutionService) TerminateWorkflow(ctx context.Context, in *TerminateWorkflowRequest, opts ...grpc.CallOption) (*TerminateWorkflowResponse, error) {
	client := v1.NewWorkflowExecutionServiceClient(m.cli.Conn())
	return client.TerminateWorkflow(ctx, in, opts...)
}
