// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: platform.proto

package platforminnerservice

import (
	"context"

	"github.com/og-game/game-proto/proto-gen-go/platform/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GameInfo           = v1.GameInfo
	GetGameLinkReq     = v1.GetGameLinkReq
	GetGameLinkResp    = v1.GetGameLinkResp
	GetGameListReq     = v1.GetGameListReq
	GetGameListResp    = v1.GetGameListResp
	GetUserBalanceReq  = v1.GetUserBalanceReq
	GetUserBalanceResp = v1.GetUserBalanceResp
	TransferReq        = v1.TransferReq
	TransferResp       = v1.TransferResp

	PlatformInnerService interface {
		// 获取游戏链接
		GetGameLink(ctx context.Context, in *GetGameLinkReq, opts ...grpc.CallOption) (*GetGameLinkResp, error)
		GetUserBalance(ctx context.Context, in *GetUserBalanceReq, opts ...grpc.CallOption) (*GetUserBalanceResp, error)
		// 转账
		Transfer(ctx context.Context, in *TransferReq, opts ...grpc.CallOption) (*TransferResp, error)
		// 获取厂商游戏列表
		GetGameList(ctx context.Context, in *GetGameListReq, opts ...grpc.CallOption) (*GetGameListResp, error)
	}

	defaultPlatformInnerService struct {
		cli zrpc.Client
	}
)

func NewPlatformInnerService(cli zrpc.Client) PlatformInnerService {
	return &defaultPlatformInnerService{
		cli: cli,
	}
}

// 获取游戏链接
func (m *defaultPlatformInnerService) GetGameLink(ctx context.Context, in *GetGameLinkReq, opts ...grpc.CallOption) (*GetGameLinkResp, error) {
	client := v1.NewPlatformInnerServiceClient(m.cli.Conn())
	return client.GetGameLink(ctx, in, opts...)
}

func (m *defaultPlatformInnerService) GetUserBalance(ctx context.Context, in *GetUserBalanceReq, opts ...grpc.CallOption) (*GetUserBalanceResp, error) {
	client := v1.NewPlatformInnerServiceClient(m.cli.Conn())
	return client.GetUserBalance(ctx, in, opts...)
}

// 转账
func (m *defaultPlatformInnerService) Transfer(ctx context.Context, in *TransferReq, opts ...grpc.CallOption) (*TransferResp, error) {
	client := v1.NewPlatformInnerServiceClient(m.cli.Conn())
	return client.Transfer(ctx, in, opts...)
}

// 获取厂商游戏列表
func (m *defaultPlatformInnerService) GetGameList(ctx context.Context, in *GetGameListReq, opts ...grpc.CallOption) (*GetGameListResp, error) {
	client := v1.NewPlatformInnerServiceClient(m.cli.Conn())
	return client.GetGameList(ctx, in, opts...)
}
