// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: temporal.proto

package workflowinteractionservice

import (
	"context"

	"github.com/og-game/game-proto/proto-gen-go/temporal/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchStartWorkflowRequest  = v1.BatchStartWorkflowRequest
	BatchStartWorkflowResponse = v1.BatchStartWorkflowResponse
	CancelWorkflowRequest      = v1.CancelWorkflowRequest
	CancelWorkflowResponse     = v1.CancelWorkflowResponse
	CreateScheduleRequest      = v1.CreateScheduleRequest
	CreateScheduleResponse     = v1.CreateScheduleResponse
	DeleteScheduleRequest      = v1.DeleteScheduleRequest
	DeleteScheduleResponse     = v1.DeleteScheduleResponse
	GetScheduleRequest         = v1.GetScheduleRequest
	GetScheduleResponse        = v1.GetScheduleResponse
	GetWorkflowHistoryRequest  = v1.GetWorkflowHistoryRequest
	GetWorkflowHistoryResponse = v1.GetWorkflowHistoryResponse
	GetWorkflowStatusRequest   = v1.GetWorkflowStatusRequest
	GetWorkflowStatusResponse  = v1.GetWorkflowStatusResponse
	ListSchedulesRequest       = v1.ListSchedulesRequest
	ListSchedulesResponse      = v1.ListSchedulesResponse
	ListWorkflowsRequest       = v1.ListWorkflowsRequest
	ListWorkflowsResponse      = v1.ListWorkflowsResponse
	PauseScheduleRequest       = v1.PauseScheduleRequest
	PauseScheduleResponse      = v1.PauseScheduleResponse
	QueryWorkflowRequest       = v1.QueryWorkflowRequest
	QueryWorkflowResponse      = v1.QueryWorkflowResponse
	ScheduleInfo               = v1.ScheduleInfo
	SignalWithStartRequest     = v1.SignalWithStartRequest
	SignalWithStartResponse    = v1.SignalWithStartResponse
	SignalWorkflowRequest      = v1.SignalWorkflowRequest
	SignalWorkflowResponse     = v1.SignalWorkflowResponse
	StartWorkflowRequest       = v1.StartWorkflowRequest
	StartWorkflowResponse      = v1.StartWorkflowResponse
	TerminateWorkflowRequest   = v1.TerminateWorkflowRequest
	TerminateWorkflowResponse  = v1.TerminateWorkflowResponse
	WorkflowEvent              = v1.WorkflowEvent
	WorkflowInfo               = v1.WorkflowInfo

	WorkflowInteractionService interface {
		// 发送信号到工作流
		SignalWorkflow(ctx context.Context, in *SignalWorkflowRequest, opts ...grpc.CallOption) (*SignalWorkflowResponse, error)
		// 查询工作流 (用于信号前的状态检查)
		QueryWorkflow(ctx context.Context, in *QueryWorkflowRequest, opts ...grpc.CallOption) (*QueryWorkflowResponse, error)
		// 信号并启动工作流 (如果工作流不存在则启动)
		SignalWithStart(ctx context.Context, in *SignalWithStartRequest, opts ...grpc.CallOption) (*SignalWithStartResponse, error)
	}

	defaultWorkflowInteractionService struct {
		cli zrpc.Client
	}
)

func NewWorkflowInteractionService(cli zrpc.Client) WorkflowInteractionService {
	return &defaultWorkflowInteractionService{
		cli: cli,
	}
}

// 发送信号到工作流
func (m *defaultWorkflowInteractionService) SignalWorkflow(ctx context.Context, in *SignalWorkflowRequest, opts ...grpc.CallOption) (*SignalWorkflowResponse, error) {
	client := v1.NewWorkflowInteractionServiceClient(m.cli.Conn())
	return client.SignalWorkflow(ctx, in, opts...)
}

// 查询工作流 (用于信号前的状态检查)
func (m *defaultWorkflowInteractionService) QueryWorkflow(ctx context.Context, in *QueryWorkflowRequest, opts ...grpc.CallOption) (*QueryWorkflowResponse, error) {
	client := v1.NewWorkflowInteractionServiceClient(m.cli.Conn())
	return client.QueryWorkflow(ctx, in, opts...)
}

// 信号并启动工作流 (如果工作流不存在则启动)
func (m *defaultWorkflowInteractionService) SignalWithStart(ctx context.Context, in *SignalWithStartRequest, opts ...grpc.CallOption) (*SignalWithStartResponse, error) {
	client := v1.NewWorkflowInteractionServiceClient(m.cli.Conn())
	return client.SignalWithStart(ctx, in, opts...)
}
