// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: fund/v1/fund.proto

package v1

import (
	v1 "github.com/og-game/game-proto/proto-gen-go/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FundReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FundReq) Reset() {
	*x = FundReq{}
	mi := &file_fund_v1_fund_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FundReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundReq) ProtoMessage() {}

func (x *FundReq) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundReq.ProtoReflect.Descriptor instead.
func (*FundReq) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{0}
}

type FundReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FundReply) Reset() {
	*x = FundReply{}
	mi := &file_fund_v1_fund_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FundReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundReply) ProtoMessage() {}

func (x *FundReply) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundReply.ProtoReflect.Descriptor instead.
func (*FundReply) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{1}
}

// 获取单个用户余额请求
type GetUserBalanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlatformId    int64                  `protobuf:"varint,2,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBalanceReq) Reset() {
	*x = GetUserBalanceReq{}
	mi := &file_fund_v1_fund_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBalanceReq) ProtoMessage() {}

func (x *GetUserBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBalanceReq.ProtoReflect.Descriptor instead.
func (*GetUserBalanceReq) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserBalanceReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserBalanceReq) GetPlatformId() int64 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

// 获取单个用户余额响应
type GetUserBalanceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       float64                `protobuf:"fixed64,1,opt,name=balance,proto3" json:"balance,omitempty"` // 游戏内余额
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`  // 版本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBalanceReply) Reset() {
	*x = GetUserBalanceReply{}
	mi := &file_fund_v1_fund_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBalanceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBalanceReply) ProtoMessage() {}

func (x *GetUserBalanceReply) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBalanceReply.ProtoReflect.Descriptor instead.
func (*GetUserBalanceReply) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserBalanceReply) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetUserBalanceReply) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// 用户余额信息
type UserBalanceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       float64                `protobuf:"fixed64,1,opt,name=balance,proto3" json:"balance,omitempty"` // 游戏内余额
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`  // 版本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBalanceInfo) Reset() {
	*x = UserBalanceInfo{}
	mi := &file_fund_v1_fund_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBalanceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBalanceInfo) ProtoMessage() {}

func (x *UserBalanceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBalanceInfo.ProtoReflect.Descriptor instead.
func (*UserBalanceInfo) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{4}
}

func (x *UserBalanceInfo) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *UserBalanceInfo) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// 批量获取用户余额请求
type GetUserBalanceListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlatformIds   []int64                `protobuf:"varint,2,rep,packed,name=platform_ids,json=platformIds,proto3" json:"platform_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBalanceListReq) Reset() {
	*x = GetUserBalanceListReq{}
	mi := &file_fund_v1_fund_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBalanceListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBalanceListReq) ProtoMessage() {}

func (x *GetUserBalanceListReq) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBalanceListReq.ProtoReflect.Descriptor instead.
func (*GetUserBalanceListReq) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserBalanceListReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserBalanceListReq) GetPlatformIds() []int64 {
	if x != nil {
		return x.PlatformIds
	}
	return nil
}

// 批量获取用户余额响应
type GetUserBalanceListReply struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Balances      map[int64]*UserBalanceInfo `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // platform_id => balance
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBalanceListReply) Reset() {
	*x = GetUserBalanceListReply{}
	mi := &file_fund_v1_fund_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBalanceListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBalanceListReply) ProtoMessage() {}

func (x *GetUserBalanceListReply) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBalanceListReply.ProtoReflect.Descriptor instead.
func (*GetUserBalanceListReply) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserBalanceListReply) GetBalances() map[int64]*UserBalanceInfo {
	if x != nil {
		return x.Balances
	}
	return nil
}

// 交易请求消息
type TransactionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          v1.TransactionType     `protobuf:"varint,1,opt,name=type,proto3,enum=common.v1.TransactionType" json:"type,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GameId        int64                  `protobuf:"varint,3,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	PlatformId    int64                  `protobuf:"varint,4,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`                // 需要变动的金额 >=0
	OrderId       string                 `protobuf:"bytes,6,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // 订单ID
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`        // 描述备注
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionReq) Reset() {
	*x = TransactionReq{}
	mi := &file_fund_v1_fund_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionReq) ProtoMessage() {}

func (x *TransactionReq) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionReq.ProtoReflect.Descriptor instead.
func (*TransactionReq) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{7}
}

func (x *TransactionReq) GetType() v1.TransactionType {
	if x != nil {
		return x.Type
	}
	return v1.TransactionType(0)
}

func (x *TransactionReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TransactionReq) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *TransactionReq) GetPlatformId() int64 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

func (x *TransactionReq) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *TransactionReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TransactionReq) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 交易响应消息
type TransactionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                   // 是否成功
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`   // 账变记录ID
	BalanceBefore float64                `protobuf:"fixed64,3,opt,name=balance_before,json=balanceBefore,proto3" json:"balance_before,omitempty"` // 变更前余额
	BalanceAfter  float64                `protobuf:"fixed64,4,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`    // 变更后余额
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                               // 当前时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionReply) Reset() {
	*x = TransactionReply{}
	mi := &file_fund_v1_fund_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionReply) ProtoMessage() {}

func (x *TransactionReply) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionReply.ProtoReflect.Descriptor instead.
func (*TransactionReply) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{8}
}

func (x *TransactionReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransactionReply) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionReply) GetBalanceBefore() float64 {
	if x != nil {
		return x.BalanceBefore
	}
	return 0
}

func (x *TransactionReply) GetBalanceAfter() float64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *TransactionReply) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 批量获取用户余额请求
type UserBalanceListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlatformIds   []int64                `protobuf:"varint,2,rep,packed,name=platform_ids,json=platformIds,proto3" json:"platform_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBalanceListReq) Reset() {
	*x = UserBalanceListReq{}
	mi := &file_fund_v1_fund_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBalanceListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBalanceListReq) ProtoMessage() {}

func (x *UserBalanceListReq) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBalanceListReq.ProtoReflect.Descriptor instead.
func (*UserBalanceListReq) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{9}
}

func (x *UserBalanceListReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserBalanceListReq) GetPlatformIds() []int64 {
	if x != nil {
		return x.PlatformIds
	}
	return nil
}

// 批量获取用户余额响应
type UserBalanceListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balances      map[int64]float64      `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // platform_id => balance
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBalanceListReply) Reset() {
	*x = UserBalanceListReply{}
	mi := &file_fund_v1_fund_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBalanceListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBalanceListReply) ProtoMessage() {}

func (x *UserBalanceListReply) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBalanceListReply.ProtoReflect.Descriptor instead.
func (*UserBalanceListReply) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{10}
}

func (x *UserBalanceListReply) GetBalances() map[int64]float64 {
	if x != nil {
		return x.Balances
	}
	return nil
}

// 发起转入操作
type TransferInReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlatformId    int64                  `protobuf:"varint,2,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	ExtraParams   map[string]string      `protobuf:"bytes,4,rep,name=extra_params,json=extraParams,proto3" json:"extra_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferInReq) Reset() {
	*x = TransferInReq{}
	mi := &file_fund_v1_fund_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferInReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferInReq) ProtoMessage() {}

func (x *TransferInReq) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferInReq.ProtoReflect.Descriptor instead.
func (*TransferInReq) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{11}
}

func (x *TransferInReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TransferInReq) GetPlatformId() int64 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

func (x *TransferInReq) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferInReq) GetExtraParams() map[string]string {
	if x != nil {
		return x.ExtraParams
	}
	return nil
}

// 发起转入操作
type TransferInReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          v1.ErrorCode           `protobuf:"varint,1,opt,name=code,proto3,enum=common.v1.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // 内部交易ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferInReply) Reset() {
	*x = TransferInReply{}
	mi := &file_fund_v1_fund_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferInReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferInReply) ProtoMessage() {}

func (x *TransferInReply) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferInReply.ProtoReflect.Descriptor instead.
func (*TransferInReply) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{12}
}

func (x *TransferInReply) GetCode() v1.ErrorCode {
	if x != nil {
		return x.Code
	}
	return v1.ErrorCode(0)
}

func (x *TransferInReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TransferInReply) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

// 发起转出操作
type TransferOutReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlatformId    int64                  `protobuf:"varint,2,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	ExtraParams   map[string]string      `protobuf:"bytes,4,rep,name=extra_params,json=extraParams,proto3" json:"extra_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferOutReq) Reset() {
	*x = TransferOutReq{}
	mi := &file_fund_v1_fund_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferOutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferOutReq) ProtoMessage() {}

func (x *TransferOutReq) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferOutReq.ProtoReflect.Descriptor instead.
func (*TransferOutReq) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{13}
}

func (x *TransferOutReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TransferOutReq) GetPlatformId() int64 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

func (x *TransferOutReq) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferOutReq) GetExtraParams() map[string]string {
	if x != nil {
		return x.ExtraParams
	}
	return nil
}

// 发起转出操作
type TransferOutReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          v1.ErrorCode           `protobuf:"varint,1,opt,name=code,proto3,enum=common.v1.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`  // 内部交易ID
	Status        v1.WithdrawStatus      `protobuf:"varint,4,opt,name=status,proto3,enum=common.v1.WithdrawStatus" json:"status,omitempty"`      // 提现状态：pending, processing, completed, failed
	EstimatedTime int64                  `protobuf:"varint,5,opt,name=estimated_time,json=estimatedTime,proto3" json:"estimated_time,omitempty"` // 预计到账时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferOutReply) Reset() {
	*x = TransferOutReply{}
	mi := &file_fund_v1_fund_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferOutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferOutReply) ProtoMessage() {}

func (x *TransferOutReply) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferOutReply.ProtoReflect.Descriptor instead.
func (*TransferOutReply) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{14}
}

func (x *TransferOutReply) GetCode() v1.ErrorCode {
	if x != nil {
		return x.Code
	}
	return v1.ErrorCode(0)
}

func (x *TransferOutReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TransferOutReply) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransferOutReply) GetStatus() v1.WithdrawStatus {
	if x != nil {
		return x.Status
	}
	return v1.WithdrawStatus(0)
}

func (x *TransferOutReply) GetEstimatedTime() int64 {
	if x != nil {
		return x.EstimatedTime
	}
	return 0
}

// 查询提现状态请求
type TransferOutProgressReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TransactionIds []string               `protobuf:"bytes,2,rep,name=transaction_ids,json=transactionIds,proto3" json:"transaction_ids,omitempty"` // 交易ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransferOutProgressReq) Reset() {
	*x = TransferOutProgressReq{}
	mi := &file_fund_v1_fund_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferOutProgressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferOutProgressReq) ProtoMessage() {}

func (x *TransferOutProgressReq) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferOutProgressReq.ProtoReflect.Descriptor instead.
func (*TransferOutProgressReq) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{15}
}

func (x *TransferOutProgressReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TransferOutProgressReq) GetTransactionIds() []string {
	if x != nil {
		return x.TransactionIds
	}
	return nil
}

type TransferOutProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          v1.ErrorCode           `protobuf:"varint,1,opt,name=code,proto3,enum=common.v1.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`  // 内部交易ID
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`                                   // 提现金额
	Status        v1.WithdrawStatus      `protobuf:"varint,5,opt,name=status,proto3,enum=common.v1.WithdrawStatus" json:"status,omitempty"`      // 提现状态：pending, processing, completed, failed
	CreatedTime   int64                  `protobuf:"varint,6,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`       // 申请时间戳
	UpdatedTime   int64                  `protobuf:"varint,7,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`       // 最后更新时间戳
	EstimatedTime int64                  `protobuf:"varint,8,opt,name=estimated_time,json=estimatedTime,proto3" json:"estimated_time,omitempty"` // 预计到账时间戳
	FailureReason string                 `protobuf:"bytes,9,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`  // 失败原因（如果状态为failed）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferOutProgress) Reset() {
	*x = TransferOutProgress{}
	mi := &file_fund_v1_fund_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferOutProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferOutProgress) ProtoMessage() {}

func (x *TransferOutProgress) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferOutProgress.ProtoReflect.Descriptor instead.
func (*TransferOutProgress) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{16}
}

func (x *TransferOutProgress) GetCode() v1.ErrorCode {
	if x != nil {
		return x.Code
	}
	return v1.ErrorCode(0)
}

func (x *TransferOutProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TransferOutProgress) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransferOutProgress) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferOutProgress) GetStatus() v1.WithdrawStatus {
	if x != nil {
		return x.Status
	}
	return v1.WithdrawStatus(0)
}

func (x *TransferOutProgress) GetCreatedTime() int64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

func (x *TransferOutProgress) GetUpdatedTime() int64 {
	if x != nil {
		return x.UpdatedTime
	}
	return 0
}

func (x *TransferOutProgress) GetEstimatedTime() int64 {
	if x != nil {
		return x.EstimatedTime
	}
	return 0
}

func (x *TransferOutProgress) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

// 查询提现状态响应
type TransferOutProgressReply struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Progress      map[string]*TransferOutProgress `protobuf:"bytes,4,rep,name=progress,proto3" json:"progress,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // transaction_id => progress
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferOutProgressReply) Reset() {
	*x = TransferOutProgressReply{}
	mi := &file_fund_v1_fund_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferOutProgressReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferOutProgressReply) ProtoMessage() {}

func (x *TransferOutProgressReply) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferOutProgressReply.ProtoReflect.Descriptor instead.
func (*TransferOutProgressReply) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{17}
}

func (x *TransferOutProgressReply) GetProgress() map[string]*TransferOutProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

var File_fund_v1_fund_proto protoreflect.FileDescriptor

const file_fund_v1_fund_proto_rawDesc = "" +
	"\n" +
	"\x12fund/v1/fund.proto\x12\afund.v1\x1a\x14common/v1/enum.proto\"\t\n" +
	"\aFundReq\"\v\n" +
	"\tFundReply\"M\n" +
	"\x11GetUserBalanceReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vplatform_id\x18\x02 \x01(\x03R\n" +
	"platformId\"I\n" +
	"\x13GetUserBalanceReply\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x01R\abalance\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\"E\n" +
	"\x0fUserBalanceInfo\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x01R\abalance\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\"S\n" +
	"\x15GetUserBalanceListReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\fplatform_ids\x18\x02 \x03(\x03R\vplatformIds\"\xbc\x01\n" +
	"\x17GetUserBalanceListReply\x12J\n" +
	"\bbalances\x18\x01 \x03(\v2..fund.v1.GetUserBalanceListReply.BalancesEntryR\bbalances\x1aU\n" +
	"\rBalancesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.fund.v1.UserBalanceInfoR\x05value:\x028\x01\"\xe8\x02\n" +
	"\x0eTransactionReq\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.common.v1.TransactionTypeR\x04type\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x17\n" +
	"\agame_id\x18\x03 \x01(\x03R\x06gameId\x12\x1f\n" +
	"\vplatform_id\x18\x04 \x01(\x03R\n" +
	"platformId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x19\n" +
	"\border_id\x18\x06 \x01(\tR\aorderId\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12A\n" +
	"\bmetadata\x18\b \x03(\v2%.fund.v1.TransactionReq.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbd\x01\n" +
	"\x10TransactionReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12%\n" +
	"\x0ebalance_before\x18\x03 \x01(\x01R\rbalanceBefore\x12#\n" +
	"\rbalance_after\x18\x04 \x01(\x01R\fbalanceAfter\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"P\n" +
	"\x12UserBalanceListReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\fplatform_ids\x18\x02 \x03(\x03R\vplatformIds\"\x9c\x01\n" +
	"\x14UserBalanceListReply\x12G\n" +
	"\bbalances\x18\x01 \x03(\v2+.fund.v1.UserBalanceListReply.BalancesEntryR\bbalances\x1a;\n" +
	"\rBalancesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xed\x01\n" +
	"\rTransferInReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vplatform_id\x18\x02 \x01(\x03R\n" +
	"platformId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12J\n" +
	"\fextra_params\x18\x04 \x03(\v2'.fund.v1.TransferInReq.ExtraParamsEntryR\vextraParams\x1a>\n" +
	"\x10ExtraParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"|\n" +
	"\x0fTransferInReply\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.common.v1.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\"\xef\x01\n" +
	"\x0eTransferOutReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vplatform_id\x18\x02 \x01(\x03R\n" +
	"platformId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12K\n" +
	"\fextra_params\x18\x04 \x03(\v2(.fund.v1.TransferOutReq.ExtraParamsEntryR\vextraParams\x1a>\n" +
	"\x10ExtraParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd7\x01\n" +
	"\x10TransferOutReply\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.common.v1.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x121\n" +
	"\x06status\x18\x04 \x01(\x0e2\x19.common.v1.WithdrawStatusR\x06status\x12%\n" +
	"\x0eestimated_time\x18\x05 \x01(\x03R\restimatedTime\"Z\n" +
	"\x16TransferOutProgressReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12'\n" +
	"\x0ftransaction_ids\x18\x02 \x03(\tR\x0etransactionIds\"\xdf\x02\n" +
	"\x13TransferOutProgress\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.common.v1.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x121\n" +
	"\x06status\x18\x05 \x01(\x0e2\x19.common.v1.WithdrawStatusR\x06status\x12!\n" +
	"\fcreated_time\x18\x06 \x01(\x03R\vcreatedTime\x12!\n" +
	"\fupdated_time\x18\a \x01(\x03R\vupdatedTime\x12%\n" +
	"\x0eestimated_time\x18\b \x01(\x03R\restimatedTime\x12%\n" +
	"\x0efailure_reason\x18\t \x01(\tR\rfailureReason\"\xc2\x01\n" +
	"\x18TransferOutProgressReply\x12K\n" +
	"\bprogress\x18\x04 \x03(\v2/.fund.v1.TransferOutProgressReply.ProgressEntryR\bprogress\x1aY\n" +
	"\rProgressEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.fund.v1.TransferOutProgressR\x05value:\x028\x012\x80\x02\n" +
	"\x10FundInnerService\x12J\n" +
	"\x0eGetUserBalance\x12\x1a.fund.v1.GetUserBalanceReq\x1a\x1c.fund.v1.GetUserBalanceReply\x12V\n" +
	"\x12GetUserBalanceList\x12\x1e.fund.v1.GetUserBalanceListReq\x1a .fund.v1.GetUserBalanceListReply\x12H\n" +
	"\x12ProcessTransaction\x12\x17.fund.v1.TransactionReq\x1a\x19.fund.v1.TransactionReply2\xc3\x02\n" +
	"\x0eFundApiService\x12P\n" +
	"\x12GetUserBalanceList\x12\x1b.fund.v1.UserBalanceListReq\x1a\x1d.fund.v1.UserBalanceListReply\x12>\n" +
	"\n" +
	"TransferIn\x12\x16.fund.v1.TransferInReq\x1a\x18.fund.v1.TransferInReply\x12A\n" +
	"\vTransferOut\x12\x17.fund.v1.TransferOutReq\x1a\x19.fund.v1.TransferOutReply\x12\\\n" +
	"\x16GetTransferOutProgress\x12\x1f.fund.v1.TransferOutProgressReq\x1a!.fund.v1.TransferOutProgressReplyB4Z2github.com/og-game/game-proto/proto-gen-go/fund/v1b\x06proto3"

var (
	file_fund_v1_fund_proto_rawDescOnce sync.Once
	file_fund_v1_fund_proto_rawDescData []byte
)

func file_fund_v1_fund_proto_rawDescGZIP() []byte {
	file_fund_v1_fund_proto_rawDescOnce.Do(func() {
		file_fund_v1_fund_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fund_v1_fund_proto_rawDesc), len(file_fund_v1_fund_proto_rawDesc)))
	})
	return file_fund_v1_fund_proto_rawDescData
}

var file_fund_v1_fund_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_fund_v1_fund_proto_goTypes = []any{
	(*FundReq)(nil),                  // 0: fund.v1.FundReq
	(*FundReply)(nil),                // 1: fund.v1.FundReply
	(*GetUserBalanceReq)(nil),        // 2: fund.v1.GetUserBalanceReq
	(*GetUserBalanceReply)(nil),      // 3: fund.v1.GetUserBalanceReply
	(*UserBalanceInfo)(nil),          // 4: fund.v1.UserBalanceInfo
	(*GetUserBalanceListReq)(nil),    // 5: fund.v1.GetUserBalanceListReq
	(*GetUserBalanceListReply)(nil),  // 6: fund.v1.GetUserBalanceListReply
	(*TransactionReq)(nil),           // 7: fund.v1.TransactionReq
	(*TransactionReply)(nil),         // 8: fund.v1.TransactionReply
	(*UserBalanceListReq)(nil),       // 9: fund.v1.UserBalanceListReq
	(*UserBalanceListReply)(nil),     // 10: fund.v1.UserBalanceListReply
	(*TransferInReq)(nil),            // 11: fund.v1.TransferInReq
	(*TransferInReply)(nil),          // 12: fund.v1.TransferInReply
	(*TransferOutReq)(nil),           // 13: fund.v1.TransferOutReq
	(*TransferOutReply)(nil),         // 14: fund.v1.TransferOutReply
	(*TransferOutProgressReq)(nil),   // 15: fund.v1.TransferOutProgressReq
	(*TransferOutProgress)(nil),      // 16: fund.v1.TransferOutProgress
	(*TransferOutProgressReply)(nil), // 17: fund.v1.TransferOutProgressReply
	nil,                              // 18: fund.v1.GetUserBalanceListReply.BalancesEntry
	nil,                              // 19: fund.v1.TransactionReq.MetadataEntry
	nil,                              // 20: fund.v1.UserBalanceListReply.BalancesEntry
	nil,                              // 21: fund.v1.TransferInReq.ExtraParamsEntry
	nil,                              // 22: fund.v1.TransferOutReq.ExtraParamsEntry
	nil,                              // 23: fund.v1.TransferOutProgressReply.ProgressEntry
	(v1.TransactionType)(0),          // 24: common.v1.TransactionType
	(v1.ErrorCode)(0),                // 25: common.v1.ErrorCode
	(v1.WithdrawStatus)(0),           // 26: common.v1.WithdrawStatus
}
var file_fund_v1_fund_proto_depIdxs = []int32{
	18, // 0: fund.v1.GetUserBalanceListReply.balances:type_name -> fund.v1.GetUserBalanceListReply.BalancesEntry
	24, // 1: fund.v1.TransactionReq.type:type_name -> common.v1.TransactionType
	19, // 2: fund.v1.TransactionReq.metadata:type_name -> fund.v1.TransactionReq.MetadataEntry
	20, // 3: fund.v1.UserBalanceListReply.balances:type_name -> fund.v1.UserBalanceListReply.BalancesEntry
	21, // 4: fund.v1.TransferInReq.extra_params:type_name -> fund.v1.TransferInReq.ExtraParamsEntry
	25, // 5: fund.v1.TransferInReply.code:type_name -> common.v1.ErrorCode
	22, // 6: fund.v1.TransferOutReq.extra_params:type_name -> fund.v1.TransferOutReq.ExtraParamsEntry
	25, // 7: fund.v1.TransferOutReply.code:type_name -> common.v1.ErrorCode
	26, // 8: fund.v1.TransferOutReply.status:type_name -> common.v1.WithdrawStatus
	25, // 9: fund.v1.TransferOutProgress.code:type_name -> common.v1.ErrorCode
	26, // 10: fund.v1.TransferOutProgress.status:type_name -> common.v1.WithdrawStatus
	23, // 11: fund.v1.TransferOutProgressReply.progress:type_name -> fund.v1.TransferOutProgressReply.ProgressEntry
	4,  // 12: fund.v1.GetUserBalanceListReply.BalancesEntry.value:type_name -> fund.v1.UserBalanceInfo
	16, // 13: fund.v1.TransferOutProgressReply.ProgressEntry.value:type_name -> fund.v1.TransferOutProgress
	2,  // 14: fund.v1.FundInnerService.GetUserBalance:input_type -> fund.v1.GetUserBalanceReq
	5,  // 15: fund.v1.FundInnerService.GetUserBalanceList:input_type -> fund.v1.GetUserBalanceListReq
	7,  // 16: fund.v1.FundInnerService.ProcessTransaction:input_type -> fund.v1.TransactionReq
	9,  // 17: fund.v1.FundApiService.GetUserBalanceList:input_type -> fund.v1.UserBalanceListReq
	11, // 18: fund.v1.FundApiService.TransferIn:input_type -> fund.v1.TransferInReq
	13, // 19: fund.v1.FundApiService.TransferOut:input_type -> fund.v1.TransferOutReq
	15, // 20: fund.v1.FundApiService.GetTransferOutProgress:input_type -> fund.v1.TransferOutProgressReq
	3,  // 21: fund.v1.FundInnerService.GetUserBalance:output_type -> fund.v1.GetUserBalanceReply
	6,  // 22: fund.v1.FundInnerService.GetUserBalanceList:output_type -> fund.v1.GetUserBalanceListReply
	8,  // 23: fund.v1.FundInnerService.ProcessTransaction:output_type -> fund.v1.TransactionReply
	10, // 24: fund.v1.FundApiService.GetUserBalanceList:output_type -> fund.v1.UserBalanceListReply
	12, // 25: fund.v1.FundApiService.TransferIn:output_type -> fund.v1.TransferInReply
	14, // 26: fund.v1.FundApiService.TransferOut:output_type -> fund.v1.TransferOutReply
	17, // 27: fund.v1.FundApiService.GetTransferOutProgress:output_type -> fund.v1.TransferOutProgressReply
	21, // [21:28] is the sub-list for method output_type
	14, // [14:21] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_fund_v1_fund_proto_init() }
func file_fund_v1_fund_proto_init() {
	if File_fund_v1_fund_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fund_v1_fund_proto_rawDesc), len(file_fund_v1_fund_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_fund_v1_fund_proto_goTypes,
		DependencyIndexes: file_fund_v1_fund_proto_depIdxs,
		MessageInfos:      file_fund_v1_fund_proto_msgTypes,
	}.Build()
	File_fund_v1_fund_proto = out.File
	file_fund_v1_fund_proto_goTypes = nil
	file_fund_v1_fund_proto_depIdxs = nil
}
