// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: fund/v1/fund.proto

package v1

import (
	v1 "github.com/og-game/game-proto/proto-gen-go/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FundReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FundReq) Reset() {
	*x = FundReq{}
	mi := &file_fund_v1_fund_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FundReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundReq) ProtoMessage() {}

func (x *FundReq) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundReq.ProtoReflect.Descriptor instead.
func (*FundReq) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{0}
}

type FundReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FundReply) Reset() {
	*x = FundReply{}
	mi := &file_fund_v1_fund_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FundReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundReply) ProtoMessage() {}

func (x *FundReply) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundReply.ProtoReflect.Descriptor instead.
func (*FundReply) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{1}
}

// 获取单个用户余额请求
type GetUserBalanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MerchantId    int64                  `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	PlatformId    int64                  `protobuf:"varint,3,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBalanceReq) Reset() {
	*x = GetUserBalanceReq{}
	mi := &file_fund_v1_fund_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBalanceReq) ProtoMessage() {}

func (x *GetUserBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBalanceReq.ProtoReflect.Descriptor instead.
func (*GetUserBalanceReq) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserBalanceReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserBalanceReq) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *GetUserBalanceReq) GetPlatformId() int64 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

// 用户余额信息
type UserBalanceInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Balance             float64                `protobuf:"fixed64,1,opt,name=balance,proto3" json:"balance,omitempty"`                                                    // 游戏内余额
	FrozenBalance       float64                `protobuf:"fixed64,2,opt,name=frozen_balance,json=frozenBalance,proto3" json:"frozen_balance,omitempty"`                   // 游戏内冻结余额
	TransferringBalance float64                `protobuf:"fixed64,3,opt,name=transferring_balance,json=transferringBalance,proto3" json:"transferring_balance,omitempty"` // 转账中余额
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UserBalanceInfo) Reset() {
	*x = UserBalanceInfo{}
	mi := &file_fund_v1_fund_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBalanceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBalanceInfo) ProtoMessage() {}

func (x *UserBalanceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBalanceInfo.ProtoReflect.Descriptor instead.
func (*UserBalanceInfo) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{3}
}

func (x *UserBalanceInfo) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *UserBalanceInfo) GetFrozenBalance() float64 {
	if x != nil {
		return x.FrozenBalance
	}
	return 0
}

func (x *UserBalanceInfo) GetTransferringBalance() float64 {
	if x != nil {
		return x.TransferringBalance
	}
	return 0
}

// 获取单个用户余额响应
type GetUserBalanceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       *UserBalanceInfo       `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBalanceReply) Reset() {
	*x = GetUserBalanceReply{}
	mi := &file_fund_v1_fund_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBalanceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBalanceReply) ProtoMessage() {}

func (x *GetUserBalanceReply) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBalanceReply.ProtoReflect.Descriptor instead.
func (*GetUserBalanceReply) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserBalanceReply) GetBalance() *UserBalanceInfo {
	if x != nil {
		return x.Balance
	}
	return nil
}

// 批量获取用户余额请求
type GetUserBalanceListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MerchantId    int64                  `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	PlatformId    int64                  `protobuf:"varint,3,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBalanceListReq) Reset() {
	*x = GetUserBalanceListReq{}
	mi := &file_fund_v1_fund_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBalanceListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBalanceListReq) ProtoMessage() {}

func (x *GetUserBalanceListReq) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBalanceListReq.ProtoReflect.Descriptor instead.
func (*GetUserBalanceListReq) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserBalanceListReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserBalanceListReq) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *GetUserBalanceListReq) GetPlatformId() int64 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

// 批量获取用户余额响应
type GetUserBalanceListReply struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Balances      map[int64]*UserBalanceInfo `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // platform_id => UserBalanceInfo
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBalanceListReply) Reset() {
	*x = GetUserBalanceListReply{}
	mi := &file_fund_v1_fund_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBalanceListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBalanceListReply) ProtoMessage() {}

func (x *GetUserBalanceListReply) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBalanceListReply.ProtoReflect.Descriptor instead.
func (*GetUserBalanceListReply) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserBalanceListReply) GetBalances() map[int64]*UserBalanceInfo {
	if x != nil {
		return x.Balances
	}
	return nil
}

// 交易请求消息
type TransactionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          v1.TransactionType     `protobuf:"varint,1,opt,name=type,proto3,enum=common.v1.TransactionType" json:"type,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MerchantId    int64                  `protobuf:"varint,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	PlatformId    int64                  `protobuf:"varint,4,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`                // 需要变动的金额 >=0
	OrderId       string                 `protobuf:"bytes,6,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // 订单ID
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`        // 描述备注
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionReq) Reset() {
	*x = TransactionReq{}
	mi := &file_fund_v1_fund_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionReq) ProtoMessage() {}

func (x *TransactionReq) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionReq.ProtoReflect.Descriptor instead.
func (*TransactionReq) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{7}
}

func (x *TransactionReq) GetType() v1.TransactionType {
	if x != nil {
		return x.Type
	}
	return v1.TransactionType(0)
}

func (x *TransactionReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TransactionReq) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *TransactionReq) GetPlatformId() int64 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

func (x *TransactionReq) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *TransactionReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TransactionReq) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 交易响应消息
type TransactionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                   // 是否成功
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`   // 账变记录ID
	BalanceBefore float64                `protobuf:"fixed64,3,opt,name=balance_before,json=balanceBefore,proto3" json:"balance_before,omitempty"` // 变更前余额
	BalanceAfter  float64                `protobuf:"fixed64,4,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`    // 变更后余额
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                               // 当前时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionReply) Reset() {
	*x = TransactionReply{}
	mi := &file_fund_v1_fund_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionReply) ProtoMessage() {}

func (x *TransactionReply) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionReply.ProtoReflect.Descriptor instead.
func (*TransactionReply) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{8}
}

func (x *TransactionReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransactionReply) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionReply) GetBalanceBefore() float64 {
	if x != nil {
		return x.BalanceBefore
	}
	return 0
}

func (x *TransactionReply) GetBalanceAfter() float64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *TransactionReply) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 用户提现请求
type WithdrawReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	PlatformId    int64                  `protobuf:"varint,3,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	ExtraParams   map[string]string      `protobuf:"bytes,4,rep,name=extra_params,json=extraParams,proto3" json:"extra_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawReq) Reset() {
	*x = WithdrawReq{}
	mi := &file_fund_v1_fund_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawReq) ProtoMessage() {}

func (x *WithdrawReq) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawReq.ProtoReflect.Descriptor instead.
func (*WithdrawReq) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{9}
}

func (x *WithdrawReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WithdrawReq) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *WithdrawReq) GetPlatformId() int64 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

func (x *WithdrawReq) GetExtraParams() map[string]string {
	if x != nil {
		return x.ExtraParams
	}
	return nil
}

// 用户提现响应
type WithdrawReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`  // 内部交易ID
	Balance       float64                `protobuf:"fixed64,4,opt,name=balance,proto3" json:"balance,omitempty"`                                 // 提现后余额
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                                     // 提现状态：pending, processing, completed, failed
	EstimatedTime int64                  `protobuf:"varint,6,opt,name=estimated_time,json=estimatedTime,proto3" json:"estimated_time,omitempty"` // 预计到账时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawReply) Reset() {
	*x = WithdrawReply{}
	mi := &file_fund_v1_fund_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawReply) ProtoMessage() {}

func (x *WithdrawReply) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawReply.ProtoReflect.Descriptor instead.
func (*WithdrawReply) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{10}
}

func (x *WithdrawReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *WithdrawReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WithdrawReply) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *WithdrawReply) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *WithdrawReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WithdrawReply) GetEstimatedTime() int64 {
	if x != nil {
		return x.EstimatedTime
	}
	return 0
}

var File_fund_v1_fund_proto protoreflect.FileDescriptor

const file_fund_v1_fund_proto_rawDesc = "" +
	"\n" +
	"\x12fund/v1/fund.proto\x12\afund.v1\x1a\x14common/v1/enum.proto\"\t\n" +
	"\aFundReq\"\v\n" +
	"\tFundReply\"n\n" +
	"\x11GetUserBalanceReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x03R\n" +
	"merchantId\x12\x1f\n" +
	"\vplatform_id\x18\x03 \x01(\x03R\n" +
	"platformId\"\x85\x01\n" +
	"\x0fUserBalanceInfo\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x01R\abalance\x12%\n" +
	"\x0efrozen_balance\x18\x02 \x01(\x01R\rfrozenBalance\x121\n" +
	"\x14transferring_balance\x18\x03 \x01(\x01R\x13transferringBalance\"I\n" +
	"\x13GetUserBalanceReply\x122\n" +
	"\abalance\x18\x01 \x01(\v2\x18.fund.v1.UserBalanceInfoR\abalance\"r\n" +
	"\x15GetUserBalanceListReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x03R\n" +
	"merchantId\x12\x1f\n" +
	"\vplatform_id\x18\x03 \x01(\x03R\n" +
	"platformId\"\xbc\x01\n" +
	"\x17GetUserBalanceListReply\x12J\n" +
	"\bbalances\x18\x01 \x03(\v2..fund.v1.GetUserBalanceListReply.BalancesEntryR\bbalances\x1aU\n" +
	"\rBalancesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.fund.v1.UserBalanceInfoR\x05value:\x028\x01\"\xf0\x02\n" +
	"\x0eTransactionReq\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.common.v1.TransactionTypeR\x04type\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\x03R\n" +
	"merchantId\x12\x1f\n" +
	"\vplatform_id\x18\x04 \x01(\x03R\n" +
	"platformId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x19\n" +
	"\border_id\x18\x06 \x01(\tR\aorderId\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12A\n" +
	"\bmetadata\x18\b \x03(\v2%.fund.v1.TransactionReq.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbd\x01\n" +
	"\x10TransactionReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12%\n" +
	"\x0ebalance_before\x18\x03 \x01(\x01R\rbalanceBefore\x12#\n" +
	"\rbalance_after\x18\x04 \x01(\x01R\fbalanceAfter\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\xe9\x01\n" +
	"\vWithdrawReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1f\n" +
	"\vplatform_id\x18\x03 \x01(\x03R\n" +
	"platformId\x12H\n" +
	"\fextra_params\x18\x04 \x03(\v2%.fund.v1.WithdrawReq.ExtraParamsEntryR\vextraParams\x1a>\n" +
	"\x10ExtraParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbd\x01\n" +
	"\rWithdrawReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x12\x18\n" +
	"\abalance\x18\x04 \x01(\x01R\abalance\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12%\n" +
	"\x0eestimated_time\x18\x06 \x01(\x03R\restimatedTime2\x80\x02\n" +
	"\x10GameInnerService\x12J\n" +
	"\x0eGetUserBalance\x12\x1a.fund.v1.GetUserBalanceReq\x1a\x1c.fund.v1.GetUserBalanceReply\x12V\n" +
	"\x12GetUserBalanceList\x12\x1e.fund.v1.GetUserBalanceListReq\x1a .fund.v1.GetUserBalanceListReply\x12H\n" +
	"\x12ProcessTransaction\x12\x17.fund.v1.TransactionReq\x1a\x19.fund.v1.TransactionReply2J\n" +
	"\x0eGameApiService\x128\n" +
	"\bWithdraw\x12\x14.fund.v1.WithdrawReq\x1a\x16.fund.v1.WithdrawReplyB4Z2github.com/og-game/game-proto/proto-gen-go/fund/v1b\x06proto3"

var (
	file_fund_v1_fund_proto_rawDescOnce sync.Once
	file_fund_v1_fund_proto_rawDescData []byte
)

func file_fund_v1_fund_proto_rawDescGZIP() []byte {
	file_fund_v1_fund_proto_rawDescOnce.Do(func() {
		file_fund_v1_fund_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fund_v1_fund_proto_rawDesc), len(file_fund_v1_fund_proto_rawDesc)))
	})
	return file_fund_v1_fund_proto_rawDescData
}

var file_fund_v1_fund_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_fund_v1_fund_proto_goTypes = []any{
	(*FundReq)(nil),                 // 0: fund.v1.FundReq
	(*FundReply)(nil),               // 1: fund.v1.FundReply
	(*GetUserBalanceReq)(nil),       // 2: fund.v1.GetUserBalanceReq
	(*UserBalanceInfo)(nil),         // 3: fund.v1.UserBalanceInfo
	(*GetUserBalanceReply)(nil),     // 4: fund.v1.GetUserBalanceReply
	(*GetUserBalanceListReq)(nil),   // 5: fund.v1.GetUserBalanceListReq
	(*GetUserBalanceListReply)(nil), // 6: fund.v1.GetUserBalanceListReply
	(*TransactionReq)(nil),          // 7: fund.v1.TransactionReq
	(*TransactionReply)(nil),        // 8: fund.v1.TransactionReply
	(*WithdrawReq)(nil),             // 9: fund.v1.WithdrawReq
	(*WithdrawReply)(nil),           // 10: fund.v1.WithdrawReply
	nil,                             // 11: fund.v1.GetUserBalanceListReply.BalancesEntry
	nil,                             // 12: fund.v1.TransactionReq.MetadataEntry
	nil,                             // 13: fund.v1.WithdrawReq.ExtraParamsEntry
	(v1.TransactionType)(0),         // 14: common.v1.TransactionType
}
var file_fund_v1_fund_proto_depIdxs = []int32{
	3,  // 0: fund.v1.GetUserBalanceReply.balance:type_name -> fund.v1.UserBalanceInfo
	11, // 1: fund.v1.GetUserBalanceListReply.balances:type_name -> fund.v1.GetUserBalanceListReply.BalancesEntry
	14, // 2: fund.v1.TransactionReq.type:type_name -> common.v1.TransactionType
	12, // 3: fund.v1.TransactionReq.metadata:type_name -> fund.v1.TransactionReq.MetadataEntry
	13, // 4: fund.v1.WithdrawReq.extra_params:type_name -> fund.v1.WithdrawReq.ExtraParamsEntry
	3,  // 5: fund.v1.GetUserBalanceListReply.BalancesEntry.value:type_name -> fund.v1.UserBalanceInfo
	2,  // 6: fund.v1.GameInnerService.GetUserBalance:input_type -> fund.v1.GetUserBalanceReq
	5,  // 7: fund.v1.GameInnerService.GetUserBalanceList:input_type -> fund.v1.GetUserBalanceListReq
	7,  // 8: fund.v1.GameInnerService.ProcessTransaction:input_type -> fund.v1.TransactionReq
	9,  // 9: fund.v1.GameApiService.Withdraw:input_type -> fund.v1.WithdrawReq
	4,  // 10: fund.v1.GameInnerService.GetUserBalance:output_type -> fund.v1.GetUserBalanceReply
	6,  // 11: fund.v1.GameInnerService.GetUserBalanceList:output_type -> fund.v1.GetUserBalanceListReply
	8,  // 12: fund.v1.GameInnerService.ProcessTransaction:output_type -> fund.v1.TransactionReply
	10, // 13: fund.v1.GameApiService.Withdraw:output_type -> fund.v1.WithdrawReply
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_fund_v1_fund_proto_init() }
func file_fund_v1_fund_proto_init() {
	if File_fund_v1_fund_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fund_v1_fund_proto_rawDesc), len(file_fund_v1_fund_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_fund_v1_fund_proto_goTypes,
		DependencyIndexes: file_fund_v1_fund_proto_depIdxs,
		MessageInfos:      file_fund_v1_fund_proto_msgTypes,
	}.Build()
	File_fund_v1_fund_proto = out.File
	file_fund_v1_fund_proto_goTypes = nil
	file_fund_v1_fund_proto_depIdxs = nil
}
