// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: fund/v1/fund.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FundReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FundReq) Reset() {
	*x = FundReq{}
	mi := &file_fund_v1_fund_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FundReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundReq) ProtoMessage() {}

func (x *FundReq) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundReq.ProtoReflect.Descriptor instead.
func (*FundReq) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{0}
}

type FundReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FundReply) Reset() {
	*x = FundReply{}
	mi := &file_fund_v1_fund_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FundReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundReply) ProtoMessage() {}

func (x *FundReply) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundReply.ProtoReflect.Descriptor instead.
func (*FundReply) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{1}
}

type CreateGameAddrReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Params        map[string]string      `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameAddrReq) Reset() {
	*x = CreateGameAddrReq{}
	mi := &file_fund_v1_fund_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameAddrReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameAddrReq) ProtoMessage() {}

func (x *CreateGameAddrReq) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameAddrReq.ProtoReflect.Descriptor instead.
func (*CreateGameAddrReq) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGameAddrReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateGameAddrReq) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type CreateGameAddrReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameAddrReply) Reset() {
	*x = CreateGameAddrReply{}
	mi := &file_fund_v1_fund_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameAddrReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameAddrReply) ProtoMessage() {}

func (x *CreateGameAddrReply) ProtoReflect() protoreflect.Message {
	mi := &file_fund_v1_fund_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameAddrReply.ProtoReflect.Descriptor instead.
func (*CreateGameAddrReply) Descriptor() ([]byte, []int) {
	return file_fund_v1_fund_proto_rawDescGZIP(), []int{3}
}

func (x *CreateGameAddrReply) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

var File_fund_v1_fund_proto protoreflect.FileDescriptor

const file_fund_v1_fund_proto_rawDesc = "" +
	"\n" +
	"\x12fund/v1/fund.proto\x12\afund.v1\"\t\n" +
	"\aFundReq\"\v\n" +
	"\tFundReply\"\xa7\x01\n" +
	"\x11CreateGameAddrReq\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12>\n" +
	"\x06params\x18\x04 \x03(\v2&.fund.v1.CreateGameAddrReq.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\".\n" +
	"\x13CreateGameAddrReply\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId2@\n" +
	"\x10GameInnerService\x12,\n" +
	"\x04Test\x12\x10.fund.v1.FundReq\x1a\x12.fund.v1.FundReply2R\n" +
	"\x0eGameApiService\x12@\n" +
	"\x04Test\x12\x1a.fund.v1.CreateGameAddrReq\x1a\x1c.fund.v1.CreateGameAddrReplyB4Z2github.com/og-game/game-proto/proto-gen-go/fund/v1b\x06proto3"

var (
	file_fund_v1_fund_proto_rawDescOnce sync.Once
	file_fund_v1_fund_proto_rawDescData []byte
)

func file_fund_v1_fund_proto_rawDescGZIP() []byte {
	file_fund_v1_fund_proto_rawDescOnce.Do(func() {
		file_fund_v1_fund_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fund_v1_fund_proto_rawDesc), len(file_fund_v1_fund_proto_rawDesc)))
	})
	return file_fund_v1_fund_proto_rawDescData
}

var file_fund_v1_fund_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_fund_v1_fund_proto_goTypes = []any{
	(*FundReq)(nil),             // 0: fund.v1.FundReq
	(*FundReply)(nil),           // 1: fund.v1.FundReply
	(*CreateGameAddrReq)(nil),   // 2: fund.v1.CreateGameAddrReq
	(*CreateGameAddrReply)(nil), // 3: fund.v1.CreateGameAddrReply
	nil,                         // 4: fund.v1.CreateGameAddrReq.ParamsEntry
}
var file_fund_v1_fund_proto_depIdxs = []int32{
	4, // 0: fund.v1.CreateGameAddrReq.params:type_name -> fund.v1.CreateGameAddrReq.ParamsEntry
	0, // 1: fund.v1.GameInnerService.Test:input_type -> fund.v1.FundReq
	2, // 2: fund.v1.GameApiService.Test:input_type -> fund.v1.CreateGameAddrReq
	1, // 3: fund.v1.GameInnerService.Test:output_type -> fund.v1.FundReply
	3, // 4: fund.v1.GameApiService.Test:output_type -> fund.v1.CreateGameAddrReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fund_v1_fund_proto_init() }
func file_fund_v1_fund_proto_init() {
	if File_fund_v1_fund_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fund_v1_fund_proto_rawDesc), len(file_fund_v1_fund_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_fund_v1_fund_proto_goTypes,
		DependencyIndexes: file_fund_v1_fund_proto_depIdxs,
		MessageInfos:      file_fund_v1_fund_proto_msgTypes,
	}.Build()
	File_fund_v1_fund_proto = out.File
	file_fund_v1_fund_proto_goTypes = nil
	file_fund_v1_fund_proto_depIdxs = nil
}
