// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: notifier/v1/notifier_types.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通知服务错误码
type NotifierErrorCode int32

const (
	NotifierErrorCode_NOTIFIER_ERROR_CODE_UNSPECIFIED NotifierErrorCode = 0 // 未指定错误
	// 成功状态
	NotifierErrorCode_NOTIFIER_ERROR_CODE_SUCCESS NotifierErrorCode = 200 // 成功
	// 客户端错误 4xx
	NotifierErrorCode_NOTIFIER_ERROR_CODE_BAD_REQUEST       NotifierErrorCode = 400 // 请求参数错误
	NotifierErrorCode_NOTIFIER_ERROR_CODE_UNAUTHORIZED      NotifierErrorCode = 401 // 未授权
	NotifierErrorCode_NOTIFIER_ERROR_CODE_FORBIDDEN         NotifierErrorCode = 403 // 权限不足
	NotifierErrorCode_NOTIFIER_ERROR_CODE_NOT_FOUND         NotifierErrorCode = 404 // 资源不存在
	NotifierErrorCode_NOTIFIER_ERROR_CODE_CONFLICT          NotifierErrorCode = 409 // 资源已存在
	NotifierErrorCode_NOTIFIER_ERROR_CODE_TOO_MANY_REQUESTS NotifierErrorCode = 429 // 请求过于频繁
	// 服务端错误 5xx
	NotifierErrorCode_NOTIFIER_ERROR_CODE_INTERNAL_SERVER_ERROR NotifierErrorCode = 500 // 未知错误
	NotifierErrorCode_NOTIFIER_ERROR_CODE_TIMEOUT               NotifierErrorCode = 504 // 超时
	NotifierErrorCode_NOTIFIER_ERROR_CODE_SERVICE_UNAVAILABLE   NotifierErrorCode = 503 // 服务不可用
	NotifierErrorCode_NOTIFIER_ERROR_CODE_ENDPOINT_FAILED       NotifierErrorCode = 510 // 端点推送失败
	// 商户相关错误 600-699
	NotifierErrorCode_NOTIFIER_ERROR_CODE_MERCHANT_DISABLED NotifierErrorCode = 600 // 商户已禁用
	// 订阅相关错误 700-799
	NotifierErrorCode_NOTIFIER_ERROR_CODE_SUBSCRIPTION_LIMIT NotifierErrorCode = 700 // 订阅限制
	// 安全相关错误 800-899
	NotifierErrorCode_NOTIFIER_ERROR_CODE_SIGNATURE_INVALID NotifierErrorCode = 800 // 签名验证失败
)

// Enum value maps for NotifierErrorCode.
var (
	NotifierErrorCode_name = map[int32]string{
		0:   "NOTIFIER_ERROR_CODE_UNSPECIFIED",
		200: "NOTIFIER_ERROR_CODE_SUCCESS",
		400: "NOTIFIER_ERROR_CODE_BAD_REQUEST",
		401: "NOTIFIER_ERROR_CODE_UNAUTHORIZED",
		403: "NOTIFIER_ERROR_CODE_FORBIDDEN",
		404: "NOTIFIER_ERROR_CODE_NOT_FOUND",
		409: "NOTIFIER_ERROR_CODE_CONFLICT",
		429: "NOTIFIER_ERROR_CODE_TOO_MANY_REQUESTS",
		500: "NOTIFIER_ERROR_CODE_INTERNAL_SERVER_ERROR",
		504: "NOTIFIER_ERROR_CODE_TIMEOUT",
		503: "NOTIFIER_ERROR_CODE_SERVICE_UNAVAILABLE",
		510: "NOTIFIER_ERROR_CODE_ENDPOINT_FAILED",
		600: "NOTIFIER_ERROR_CODE_MERCHANT_DISABLED",
		700: "NOTIFIER_ERROR_CODE_SUBSCRIPTION_LIMIT",
		800: "NOTIFIER_ERROR_CODE_SIGNATURE_INVALID",
	}
	NotifierErrorCode_value = map[string]int32{
		"NOTIFIER_ERROR_CODE_UNSPECIFIED":           0,
		"NOTIFIER_ERROR_CODE_SUCCESS":               200,
		"NOTIFIER_ERROR_CODE_BAD_REQUEST":           400,
		"NOTIFIER_ERROR_CODE_UNAUTHORIZED":          401,
		"NOTIFIER_ERROR_CODE_FORBIDDEN":             403,
		"NOTIFIER_ERROR_CODE_NOT_FOUND":             404,
		"NOTIFIER_ERROR_CODE_CONFLICT":              409,
		"NOTIFIER_ERROR_CODE_TOO_MANY_REQUESTS":     429,
		"NOTIFIER_ERROR_CODE_INTERNAL_SERVER_ERROR": 500,
		"NOTIFIER_ERROR_CODE_TIMEOUT":               504,
		"NOTIFIER_ERROR_CODE_SERVICE_UNAVAILABLE":   503,
		"NOTIFIER_ERROR_CODE_ENDPOINT_FAILED":       510,
		"NOTIFIER_ERROR_CODE_MERCHANT_DISABLED":     600,
		"NOTIFIER_ERROR_CODE_SUBSCRIPTION_LIMIT":    700,
		"NOTIFIER_ERROR_CODE_SIGNATURE_INVALID":     800,
	}
)

func (x NotifierErrorCode) Enum() *NotifierErrorCode {
	p := new(NotifierErrorCode)
	*p = x
	return p
}

func (x NotifierErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotifierErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_notifier_v1_notifier_types_proto_enumTypes[0].Descriptor()
}

func (NotifierErrorCode) Type() protoreflect.EnumType {
	return &file_notifier_v1_notifier_types_proto_enumTypes[0]
}

func (x NotifierErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotifierErrorCode.Descriptor instead.
func (NotifierErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{0}
}

// 商户状态
type MerchantStatus int32

const (
	MerchantStatus_MERCHANT_STATUS_UNSPECIFIED MerchantStatus = 0
	MerchantStatus_MERCHANT_STATUS_ACTIVE      MerchantStatus = 1 // 已激活
	MerchantStatus_MERCHANT_STATUS_SUSPENDED   MerchantStatus = 2 // 暂停
	MerchantStatus_MERCHANT_STATUS_DISABLED    MerchantStatus = 3 // 已禁用
)

// Enum value maps for MerchantStatus.
var (
	MerchantStatus_name = map[int32]string{
		0: "MERCHANT_STATUS_UNSPECIFIED",
		1: "MERCHANT_STATUS_ACTIVE",
		2: "MERCHANT_STATUS_SUSPENDED",
		3: "MERCHANT_STATUS_DISABLED",
	}
	MerchantStatus_value = map[string]int32{
		"MERCHANT_STATUS_UNSPECIFIED": 0,
		"MERCHANT_STATUS_ACTIVE":      1,
		"MERCHANT_STATUS_SUSPENDED":   2,
		"MERCHANT_STATUS_DISABLED":    3,
	}
)

func (x MerchantStatus) Enum() *MerchantStatus {
	p := new(MerchantStatus)
	*p = x
	return p
}

func (x MerchantStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MerchantStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_notifier_v1_notifier_types_proto_enumTypes[1].Descriptor()
}

func (MerchantStatus) Type() protoreflect.EnumType {
	return &file_notifier_v1_notifier_types_proto_enumTypes[1]
}

func (x MerchantStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MerchantStatus.Descriptor instead.
func (MerchantStatus) EnumDescriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{1}
}

// 推送通道 - 实际使用的4种模式
type PushChannel int32

const (
	PushChannel_CHANNEL_UNSPECIFIED PushChannel = 0
	PushChannel_CHANNEL_HTTP        PushChannel = 1 // HTTP webhook
	PushChannel_CHANNEL_WEBSOCKET   PushChannel = 2 // WebSocket长连接
	PushChannel_CHANNEL_GRPC        PushChannel = 3 // gRPC流式
	PushChannel_CHANNEL_ROBOT       PushChannel = 4 // 机器人（Slack/Lark等）
)

// Enum value maps for PushChannel.
var (
	PushChannel_name = map[int32]string{
		0: "CHANNEL_UNSPECIFIED",
		1: "CHANNEL_HTTP",
		2: "CHANNEL_WEBSOCKET",
		3: "CHANNEL_GRPC",
		4: "CHANNEL_ROBOT",
	}
	PushChannel_value = map[string]int32{
		"CHANNEL_UNSPECIFIED": 0,
		"CHANNEL_HTTP":        1,
		"CHANNEL_WEBSOCKET":   2,
		"CHANNEL_GRPC":        3,
		"CHANNEL_ROBOT":       4,
	}
)

func (x PushChannel) Enum() *PushChannel {
	p := new(PushChannel)
	*p = x
	return p
}

func (x PushChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_notifier_v1_notifier_types_proto_enumTypes[2].Descriptor()
}

func (PushChannel) Type() protoreflect.EnumType {
	return &file_notifier_v1_notifier_types_proto_enumTypes[2]
}

func (x PushChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushChannel.Descriptor instead.
func (PushChannel) EnumDescriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{2}
}

// 推送状态
type PushStatus int32

const (
	PushStatus_PUSH_STATUS_UNSPECIFIED PushStatus = 0
	PushStatus_PUSH_STATUS_PENDING     PushStatus = 1 // 待推送
	PushStatus_PUSH_STATUS_SUCCESS     PushStatus = 2 // 推送成功
	PushStatus_PUSH_STATUS_FAILED      PushStatus = 3 // 推送失败
	PushStatus_PUSH_STATUS_RETRY       PushStatus = 4 // 重试中
)

// Enum value maps for PushStatus.
var (
	PushStatus_name = map[int32]string{
		0: "PUSH_STATUS_UNSPECIFIED",
		1: "PUSH_STATUS_PENDING",
		2: "PUSH_STATUS_SUCCESS",
		3: "PUSH_STATUS_FAILED",
		4: "PUSH_STATUS_RETRY",
	}
	PushStatus_value = map[string]int32{
		"PUSH_STATUS_UNSPECIFIED": 0,
		"PUSH_STATUS_PENDING":     1,
		"PUSH_STATUS_SUCCESS":     2,
		"PUSH_STATUS_FAILED":      3,
		"PUSH_STATUS_RETRY":       4,
	}
)

func (x PushStatus) Enum() *PushStatus {
	p := new(PushStatus)
	*p = x
	return p
}

func (x PushStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_notifier_v1_notifier_types_proto_enumTypes[3].Descriptor()
}

func (PushStatus) Type() protoreflect.EnumType {
	return &file_notifier_v1_notifier_types_proto_enumTypes[3]
}

func (x PushStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushStatus.Descriptor instead.
func (PushStatus) EnumDescriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{3}
}

// 通知优先级
type NotificationPriority int32

const (
	NotificationPriority_PRIORITY_UNSPECIFIED NotificationPriority = 0
	NotificationPriority_PRIORITY_LOW         NotificationPriority = 1 // 低优先级
	NotificationPriority_PRIORITY_NORMAL      NotificationPriority = 2 // 普通
	NotificationPriority_PRIORITY_HIGH        NotificationPriority = 3 // 高优先级
	NotificationPriority_PRIORITY_CRITICAL    NotificationPriority = 4 // 紧急
)

// Enum value maps for NotificationPriority.
var (
	NotificationPriority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_LOW",
		2: "PRIORITY_NORMAL",
		3: "PRIORITY_HIGH",
		4: "PRIORITY_CRITICAL",
	}
	NotificationPriority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_LOW":         1,
		"PRIORITY_NORMAL":      2,
		"PRIORITY_HIGH":        3,
		"PRIORITY_CRITICAL":    4,
	}
)

func (x NotificationPriority) Enum() *NotificationPriority {
	p := new(NotificationPriority)
	*p = x
	return p
}

func (x NotificationPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_notifier_v1_notifier_types_proto_enumTypes[4].Descriptor()
}

func (NotificationPriority) Type() protoreflect.EnumType {
	return &file_notifier_v1_notifier_types_proto_enumTypes[4]
}

func (x NotificationPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationPriority.Descriptor instead.
func (NotificationPriority) EnumDescriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{4}
}

// 通知类别 - 大类
type NotificationCategory int32

const (
	NotificationCategory_CATEGORY_UNSPECIFIED NotificationCategory = 0
	NotificationCategory_CATEGORY_SYSTEM      NotificationCategory = 1 // 系统通知
	NotificationCategory_CATEGORY_RISK        NotificationCategory = 2 // 风控通知
	NotificationCategory_CATEGORY_GAME        NotificationCategory = 3 // 游戏通知
	NotificationCategory_CATEGORY_REPORT      NotificationCategory = 4 // 报表通知
)

// Enum value maps for NotificationCategory.
var (
	NotificationCategory_name = map[int32]string{
		0: "CATEGORY_UNSPECIFIED",
		1: "CATEGORY_SYSTEM",
		2: "CATEGORY_RISK",
		3: "CATEGORY_GAME",
		4: "CATEGORY_REPORT",
	}
	NotificationCategory_value = map[string]int32{
		"CATEGORY_UNSPECIFIED": 0,
		"CATEGORY_SYSTEM":      1,
		"CATEGORY_RISK":        2,
		"CATEGORY_GAME":        3,
		"CATEGORY_REPORT":      4,
	}
)

func (x NotificationCategory) Enum() *NotificationCategory {
	p := new(NotificationCategory)
	*p = x
	return p
}

func (x NotificationCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_notifier_v1_notifier_types_proto_enumTypes[5].Descriptor()
}

func (NotificationCategory) Type() protoreflect.EnumType {
	return &file_notifier_v1_notifier_types_proto_enumTypes[5]
}

func (x NotificationCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationCategory.Descriptor instead.
func (NotificationCategory) EnumDescriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{5}
}

// 事件类型 - 小类（具体事件）
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	// 系统事件 (1xx) - CATEGORY_SYSTEM
	EventType_EVENT_TYPE_SYSTEM_MAINTENANCE  EventType = 101 // 系统维护
	EventType_EVENT_TYPE_SYSTEM_ANNOUNCEMENT EventType = 102 // 系统公告
	EventType_EVENT_TYPE_SYSTEM_UPGRADE      EventType = 103 // 系统升级
	EventType_EVENT_TYPE_SYSTEM_ERROR        EventType = 104 // 系统异常
	// 风控事件 (2xx) - CATEGORY_RISK
	EventType_EVENT_TYPE_RISK_ALERT        EventType = 201 // 风险告警
	EventType_EVENT_TYPE_BAD_DEBT          EventType = 202 // 坏账通知
	EventType_EVENT_TYPE_FRAUD_DETECTED    EventType = 203 // 欺诈检测
	EventType_EVENT_TYPE_ABNORMAL_BEHAVIOR EventType = 204 // 异常行为
	// 游戏事件 (3xx) - CATEGORY_GAME
	EventType_EVENT_TYPE_GAME_RESULT  EventType = 301 // 游戏结果
	EventType_EVENT_TYPE_GAME_BIG_WIN EventType = 302 // 大奖通知
	// 报表事件 (4xx) - CATEGORY_REPORT
	EventType_EVENT_TYPE_DAILY_REPORT   EventType = 401 // 日报
	EventType_EVENT_TYPE_WEEKLY_REPORT  EventType = 402 // 周报
	EventType_EVENT_TYPE_MONTHLY_REPORT EventType = 403 // 月报
	EventType_EVENT_TYPE_ANOMALY_REPORT EventType = 404 // 异常报告
	EventType_EVENT_TYPE_CUSTOM_REPORT  EventType = 405 // 自定义报表
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:   "EVENT_TYPE_UNSPECIFIED",
		101: "EVENT_TYPE_SYSTEM_MAINTENANCE",
		102: "EVENT_TYPE_SYSTEM_ANNOUNCEMENT",
		103: "EVENT_TYPE_SYSTEM_UPGRADE",
		104: "EVENT_TYPE_SYSTEM_ERROR",
		201: "EVENT_TYPE_RISK_ALERT",
		202: "EVENT_TYPE_BAD_DEBT",
		203: "EVENT_TYPE_FRAUD_DETECTED",
		204: "EVENT_TYPE_ABNORMAL_BEHAVIOR",
		301: "EVENT_TYPE_GAME_RESULT",
		302: "EVENT_TYPE_GAME_BIG_WIN",
		401: "EVENT_TYPE_DAILY_REPORT",
		402: "EVENT_TYPE_WEEKLY_REPORT",
		403: "EVENT_TYPE_MONTHLY_REPORT",
		404: "EVENT_TYPE_ANOMALY_REPORT",
		405: "EVENT_TYPE_CUSTOM_REPORT",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":         0,
		"EVENT_TYPE_SYSTEM_MAINTENANCE":  101,
		"EVENT_TYPE_SYSTEM_ANNOUNCEMENT": 102,
		"EVENT_TYPE_SYSTEM_UPGRADE":      103,
		"EVENT_TYPE_SYSTEM_ERROR":        104,
		"EVENT_TYPE_RISK_ALERT":          201,
		"EVENT_TYPE_BAD_DEBT":            202,
		"EVENT_TYPE_FRAUD_DETECTED":      203,
		"EVENT_TYPE_ABNORMAL_BEHAVIOR":   204,
		"EVENT_TYPE_GAME_RESULT":         301,
		"EVENT_TYPE_GAME_BIG_WIN":        302,
		"EVENT_TYPE_DAILY_REPORT":        401,
		"EVENT_TYPE_WEEKLY_REPORT":       402,
		"EVENT_TYPE_MONTHLY_REPORT":      403,
		"EVENT_TYPE_ANOMALY_REPORT":      404,
		"EVENT_TYPE_CUSTOM_REPORT":       405,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_notifier_v1_notifier_types_proto_enumTypes[6].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_notifier_v1_notifier_types_proto_enumTypes[6]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{6}
}

// 风险级别
type RiskLevel int32

const (
	RiskLevel_RISK_LEVEL_UNSPECIFIED RiskLevel = 0
	RiskLevel_RISK_LEVEL_LOW         RiskLevel = 1
	RiskLevel_RISK_LEVEL_MEDIUM      RiskLevel = 2
	RiskLevel_RISK_LEVEL_HIGH        RiskLevel = 3
	RiskLevel_RISK_LEVEL_CRITICAL    RiskLevel = 4
)

// Enum value maps for RiskLevel.
var (
	RiskLevel_name = map[int32]string{
		0: "RISK_LEVEL_UNSPECIFIED",
		1: "RISK_LEVEL_LOW",
		2: "RISK_LEVEL_MEDIUM",
		3: "RISK_LEVEL_HIGH",
		4: "RISK_LEVEL_CRITICAL",
	}
	RiskLevel_value = map[string]int32{
		"RISK_LEVEL_UNSPECIFIED": 0,
		"RISK_LEVEL_LOW":         1,
		"RISK_LEVEL_MEDIUM":      2,
		"RISK_LEVEL_HIGH":        3,
		"RISK_LEVEL_CRITICAL":    4,
	}
)

func (x RiskLevel) Enum() *RiskLevel {
	p := new(RiskLevel)
	*p = x
	return p
}

func (x RiskLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RiskLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_notifier_v1_notifier_types_proto_enumTypes[7].Descriptor()
}

func (RiskLevel) Type() protoreflect.EnumType {
	return &file_notifier_v1_notifier_types_proto_enumTypes[7]
}

func (x RiskLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RiskLevel.Descriptor instead.
func (RiskLevel) EnumDescriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{7}
}

// 风险类型
type RiskType int32

const (
	RiskType_RISK_TYPE_UNSPECIFIED      RiskType = 0
	RiskType_RISK_TYPE_FRAUD            RiskType = 1 // 欺诈
	RiskType_RISK_TYPE_ABNORMAL         RiskType = 2 // 异常
	RiskType_RISK_TYPE_SUSPICIOUS       RiskType = 3 // 可疑
	RiskType_RISK_TYPE_BLACKLIST        RiskType = 4 // 黑名单
	RiskType_RISK_TYPE_MONEY_LAUNDERING RiskType = 5 // 洗钱
)

// Enum value maps for RiskType.
var (
	RiskType_name = map[int32]string{
		0: "RISK_TYPE_UNSPECIFIED",
		1: "RISK_TYPE_FRAUD",
		2: "RISK_TYPE_ABNORMAL",
		3: "RISK_TYPE_SUSPICIOUS",
		4: "RISK_TYPE_BLACKLIST",
		5: "RISK_TYPE_MONEY_LAUNDERING",
	}
	RiskType_value = map[string]int32{
		"RISK_TYPE_UNSPECIFIED":      0,
		"RISK_TYPE_FRAUD":            1,
		"RISK_TYPE_ABNORMAL":         2,
		"RISK_TYPE_SUSPICIOUS":       3,
		"RISK_TYPE_BLACKLIST":        4,
		"RISK_TYPE_MONEY_LAUNDERING": 5,
	}
)

func (x RiskType) Enum() *RiskType {
	p := new(RiskType)
	*p = x
	return p
}

func (x RiskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RiskType) Descriptor() protoreflect.EnumDescriptor {
	return file_notifier_v1_notifier_types_proto_enumTypes[8].Descriptor()
}

func (RiskType) Type() protoreflect.EnumType {
	return &file_notifier_v1_notifier_types_proto_enumTypes[8]
}

func (x RiskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RiskType.Descriptor instead.
func (RiskType) EnumDescriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{8}
}

// 系统维护类型
type MaintenanceType int32

const (
	MaintenanceType_MAINTENANCE_TYPE_UNSPECIFIED MaintenanceType = 0
	MaintenanceType_MAINTENANCE_TYPE_SCHEDULED   MaintenanceType = 1 // 计划维护
	MaintenanceType_MAINTENANCE_TYPE_EMERGENCY   MaintenanceType = 2 // 紧急维护
	MaintenanceType_MAINTENANCE_TYPE_UPGRADE     MaintenanceType = 3 // 系统升级
)

// Enum value maps for MaintenanceType.
var (
	MaintenanceType_name = map[int32]string{
		0: "MAINTENANCE_TYPE_UNSPECIFIED",
		1: "MAINTENANCE_TYPE_SCHEDULED",
		2: "MAINTENANCE_TYPE_EMERGENCY",
		3: "MAINTENANCE_TYPE_UPGRADE",
	}
	MaintenanceType_value = map[string]int32{
		"MAINTENANCE_TYPE_UNSPECIFIED": 0,
		"MAINTENANCE_TYPE_SCHEDULED":   1,
		"MAINTENANCE_TYPE_EMERGENCY":   2,
		"MAINTENANCE_TYPE_UPGRADE":     3,
	}
)

func (x MaintenanceType) Enum() *MaintenanceType {
	p := new(MaintenanceType)
	*p = x
	return p
}

func (x MaintenanceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MaintenanceType) Descriptor() protoreflect.EnumDescriptor {
	return file_notifier_v1_notifier_types_proto_enumTypes[9].Descriptor()
}

func (MaintenanceType) Type() protoreflect.EnumType {
	return &file_notifier_v1_notifier_types_proto_enumTypes[9]
}

func (x MaintenanceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MaintenanceType.Descriptor instead.
func (MaintenanceType) EnumDescriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{9}
}

// 公告类型
type AnnouncementType int32

const (
	AnnouncementType_ANNOUNCEMENT_TYPE_UNSPECIFIED AnnouncementType = 0
	AnnouncementType_ANNOUNCEMENT_TYPE_INFO        AnnouncementType = 1 // 信息
	AnnouncementType_ANNOUNCEMENT_TYPE_WARNING     AnnouncementType = 2 // 警告
	AnnouncementType_ANNOUNCEMENT_TYPE_CRITICAL    AnnouncementType = 3 // 重要
)

// Enum value maps for AnnouncementType.
var (
	AnnouncementType_name = map[int32]string{
		0: "ANNOUNCEMENT_TYPE_UNSPECIFIED",
		1: "ANNOUNCEMENT_TYPE_INFO",
		2: "ANNOUNCEMENT_TYPE_WARNING",
		3: "ANNOUNCEMENT_TYPE_CRITICAL",
	}
	AnnouncementType_value = map[string]int32{
		"ANNOUNCEMENT_TYPE_UNSPECIFIED": 0,
		"ANNOUNCEMENT_TYPE_INFO":        1,
		"ANNOUNCEMENT_TYPE_WARNING":     2,
		"ANNOUNCEMENT_TYPE_CRITICAL":    3,
	}
)

func (x AnnouncementType) Enum() *AnnouncementType {
	p := new(AnnouncementType)
	*p = x
	return p
}

func (x AnnouncementType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnnouncementType) Descriptor() protoreflect.EnumDescriptor {
	return file_notifier_v1_notifier_types_proto_enumTypes[10].Descriptor()
}

func (AnnouncementType) Type() protoreflect.EnumType {
	return &file_notifier_v1_notifier_types_proto_enumTypes[10]
}

func (x AnnouncementType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnnouncementType.Descriptor instead.
func (AnnouncementType) EnumDescriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{10}
}

// 游戏记录状态
type GameRecordStatus int32

const (
	GameRecordStatus_GAME_STATUS_UNSPECIFIED GameRecordStatus = 0
	GameRecordStatus_GAME_STATUS_BETTING     GameRecordStatus = 1 // 投注中
	GameRecordStatus_GAME_STATUS_SETTLED     GameRecordStatus = 2 // 已结算
	GameRecordStatus_GAME_STATUS_CANCELLED   GameRecordStatus = 3 // 已取消
	GameRecordStatus_GAME_STATUS_ADJUSTED    GameRecordStatus = 4 // 已调整
)

// Enum value maps for GameRecordStatus.
var (
	GameRecordStatus_name = map[int32]string{
		0: "GAME_STATUS_UNSPECIFIED",
		1: "GAME_STATUS_BETTING",
		2: "GAME_STATUS_SETTLED",
		3: "GAME_STATUS_CANCELLED",
		4: "GAME_STATUS_ADJUSTED",
	}
	GameRecordStatus_value = map[string]int32{
		"GAME_STATUS_UNSPECIFIED": 0,
		"GAME_STATUS_BETTING":     1,
		"GAME_STATUS_SETTLED":     2,
		"GAME_STATUS_CANCELLED":   3,
		"GAME_STATUS_ADJUSTED":    4,
	}
)

func (x GameRecordStatus) Enum() *GameRecordStatus {
	p := new(GameRecordStatus)
	*p = x
	return p
}

func (x GameRecordStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameRecordStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_notifier_v1_notifier_types_proto_enumTypes[11].Descriptor()
}

func (GameRecordStatus) Type() protoreflect.EnumType {
	return &file_notifier_v1_notifier_types_proto_enumTypes[11]
}

func (x GameRecordStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameRecordStatus.Descriptor instead.
func (GameRecordStatus) EnumDescriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{11}
}

// 异常类型
type AnomalyType int32

const (
	AnomalyType_ANOMALY_TYPE_UNSPECIFIED   AnomalyType = 0
	AnomalyType_ANOMALY_TYPE_TRAFFIC       AnomalyType = 1 // 流量异常
	AnomalyType_ANOMALY_TYPE_REVENUE       AnomalyType = 2 // 收入异常
	AnomalyType_ANOMALY_TYPE_USER_BEHAVIOR AnomalyType = 3 // 用户行为异常
	AnomalyType_ANOMALY_TYPE_SYSTEM        AnomalyType = 4 // 系统异常
	AnomalyType_ANOMALY_TYPE_PAYMENT       AnomalyType = 5 // 支付异常
	AnomalyType_ANOMALY_TYPE_GAME          AnomalyType = 6 // 游戏异常
)

// Enum value maps for AnomalyType.
var (
	AnomalyType_name = map[int32]string{
		0: "ANOMALY_TYPE_UNSPECIFIED",
		1: "ANOMALY_TYPE_TRAFFIC",
		2: "ANOMALY_TYPE_REVENUE",
		3: "ANOMALY_TYPE_USER_BEHAVIOR",
		4: "ANOMALY_TYPE_SYSTEM",
		5: "ANOMALY_TYPE_PAYMENT",
		6: "ANOMALY_TYPE_GAME",
	}
	AnomalyType_value = map[string]int32{
		"ANOMALY_TYPE_UNSPECIFIED":   0,
		"ANOMALY_TYPE_TRAFFIC":       1,
		"ANOMALY_TYPE_REVENUE":       2,
		"ANOMALY_TYPE_USER_BEHAVIOR": 3,
		"ANOMALY_TYPE_SYSTEM":        4,
		"ANOMALY_TYPE_PAYMENT":       5,
		"ANOMALY_TYPE_GAME":          6,
	}
)

func (x AnomalyType) Enum() *AnomalyType {
	p := new(AnomalyType)
	*p = x
	return p
}

func (x AnomalyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnomalyType) Descriptor() protoreflect.EnumDescriptor {
	return file_notifier_v1_notifier_types_proto_enumTypes[12].Descriptor()
}

func (AnomalyType) Type() protoreflect.EnumType {
	return &file_notifier_v1_notifier_types_proto_enumTypes[12]
}

func (x AnomalyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnomalyType.Descriptor instead.
func (AnomalyType) EnumDescriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{12}
}

// 机器人类型
type RobotType int32

const (
	RobotType_ROBOT_TYPE_UNSPECIFIED RobotType = 0
	RobotType_ROBOT_TYPE_SLACK       RobotType = 1
	RobotType_ROBOT_TYPE_LARK        RobotType = 2
	RobotType_ROBOT_TYPE_TEAMS       RobotType = 3
	RobotType_ROBOT_TYPE_TELEGRAM    RobotType = 4
)

// Enum value maps for RobotType.
var (
	RobotType_name = map[int32]string{
		0: "ROBOT_TYPE_UNSPECIFIED",
		1: "ROBOT_TYPE_SLACK",
		2: "ROBOT_TYPE_LARK",
		3: "ROBOT_TYPE_TEAMS",
		4: "ROBOT_TYPE_TELEGRAM",
	}
	RobotType_value = map[string]int32{
		"ROBOT_TYPE_UNSPECIFIED": 0,
		"ROBOT_TYPE_SLACK":       1,
		"ROBOT_TYPE_LARK":        2,
		"ROBOT_TYPE_TEAMS":       3,
		"ROBOT_TYPE_TELEGRAM":    4,
	}
)

func (x RobotType) Enum() *RobotType {
	p := new(RobotType)
	*p = x
	return p
}

func (x RobotType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RobotType) Descriptor() protoreflect.EnumDescriptor {
	return file_notifier_v1_notifier_types_proto_enumTypes[13].Descriptor()
}

func (RobotType) Type() protoreflect.EnumType {
	return &file_notifier_v1_notifier_types_proto_enumTypes[13]
}

func (x RobotType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RobotType.Descriptor instead.
func (RobotType) EnumDescriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{13}
}

// 附件类型
type AttachmentType int32

const (
	AttachmentType_ATTACHMENT_TYPE_UNSPECIFIED AttachmentType = 0
	AttachmentType_ATTACHMENT_TYPE_IMAGE       AttachmentType = 1
	AttachmentType_ATTACHMENT_TYPE_FILE        AttachmentType = 2
	AttachmentType_ATTACHMENT_TYPE_LINK        AttachmentType = 3
)

// Enum value maps for AttachmentType.
var (
	AttachmentType_name = map[int32]string{
		0: "ATTACHMENT_TYPE_UNSPECIFIED",
		1: "ATTACHMENT_TYPE_IMAGE",
		2: "ATTACHMENT_TYPE_FILE",
		3: "ATTACHMENT_TYPE_LINK",
	}
	AttachmentType_value = map[string]int32{
		"ATTACHMENT_TYPE_UNSPECIFIED": 0,
		"ATTACHMENT_TYPE_IMAGE":       1,
		"ATTACHMENT_TYPE_FILE":        2,
		"ATTACHMENT_TYPE_LINK":        3,
	}
)

func (x AttachmentType) Enum() *AttachmentType {
	p := new(AttachmentType)
	*p = x
	return p
}

func (x AttachmentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttachmentType) Descriptor() protoreflect.EnumDescriptor {
	return file_notifier_v1_notifier_types_proto_enumTypes[14].Descriptor()
}

func (AttachmentType) Type() protoreflect.EnumType {
	return &file_notifier_v1_notifier_types_proto_enumTypes[14]
}

func (x AttachmentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttachmentType.Descriptor instead.
func (AttachmentType) EnumDescriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{14}
}

// 按钮动作类型
type ButtonAction int32

const (
	ButtonAction_BUTTON_ACTION_UNSPECIFIED ButtonAction = 0
	ButtonAction_BUTTON_ACTION_URL         ButtonAction = 1 // 打开URL
	ButtonAction_BUTTON_ACTION_CALLBACK    ButtonAction = 2 // 回调
	ButtonAction_BUTTON_ACTION_COMMAND     ButtonAction = 3 // 执行命令
)

// Enum value maps for ButtonAction.
var (
	ButtonAction_name = map[int32]string{
		0: "BUTTON_ACTION_UNSPECIFIED",
		1: "BUTTON_ACTION_URL",
		2: "BUTTON_ACTION_CALLBACK",
		3: "BUTTON_ACTION_COMMAND",
	}
	ButtonAction_value = map[string]int32{
		"BUTTON_ACTION_UNSPECIFIED": 0,
		"BUTTON_ACTION_URL":         1,
		"BUTTON_ACTION_CALLBACK":    2,
		"BUTTON_ACTION_COMMAND":     3,
	}
)

func (x ButtonAction) Enum() *ButtonAction {
	p := new(ButtonAction)
	*p = x
	return p
}

func (x ButtonAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ButtonAction) Descriptor() protoreflect.EnumDescriptor {
	return file_notifier_v1_notifier_types_proto_enumTypes[15].Descriptor()
}

func (ButtonAction) Type() protoreflect.EnumType {
	return &file_notifier_v1_notifier_types_proto_enumTypes[15]
}

func (x ButtonAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ButtonAction.Descriptor instead.
func (ButtonAction) EnumDescriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{15}
}

// 按钮样式
type ButtonStyle int32

const (
	ButtonStyle_BUTTON_STYLE_UNSPECIFIED ButtonStyle = 0
	ButtonStyle_BUTTON_STYLE_DEFAULT     ButtonStyle = 1
	ButtonStyle_BUTTON_STYLE_PRIMARY     ButtonStyle = 2
	ButtonStyle_BUTTON_STYLE_SUCCESS     ButtonStyle = 3
	ButtonStyle_BUTTON_STYLE_DANGER      ButtonStyle = 4
	ButtonStyle_BUTTON_STYLE_WARNING     ButtonStyle = 5
)

// Enum value maps for ButtonStyle.
var (
	ButtonStyle_name = map[int32]string{
		0: "BUTTON_STYLE_UNSPECIFIED",
		1: "BUTTON_STYLE_DEFAULT",
		2: "BUTTON_STYLE_PRIMARY",
		3: "BUTTON_STYLE_SUCCESS",
		4: "BUTTON_STYLE_DANGER",
		5: "BUTTON_STYLE_WARNING",
	}
	ButtonStyle_value = map[string]int32{
		"BUTTON_STYLE_UNSPECIFIED": 0,
		"BUTTON_STYLE_DEFAULT":     1,
		"BUTTON_STYLE_PRIMARY":     2,
		"BUTTON_STYLE_SUCCESS":     3,
		"BUTTON_STYLE_DANGER":      4,
		"BUTTON_STYLE_WARNING":     5,
	}
)

func (x ButtonStyle) Enum() *ButtonStyle {
	p := new(ButtonStyle)
	*p = x
	return p
}

func (x ButtonStyle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ButtonStyle) Descriptor() protoreflect.EnumDescriptor {
	return file_notifier_v1_notifier_types_proto_enumTypes[16].Descriptor()
}

func (ButtonStyle) Type() protoreflect.EnumType {
	return &file_notifier_v1_notifier_types_proto_enumTypes[16]
}

func (x ButtonStyle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ButtonStyle.Descriptor instead.
func (ButtonStyle) EnumDescriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{16}
}

// WebSocket帧类型
type WebSocketFrameType int32

const (
	WebSocketFrameType_WS_FRAME_UNSPECIFIED  WebSocketFrameType = 0
	WebSocketFrameType_WS_FRAME_NOTIFICATION WebSocketFrameType = 1 // 通知消息
	WebSocketFrameType_WS_FRAME_HEARTBEAT    WebSocketFrameType = 2 // 心跳
	WebSocketFrameType_WS_FRAME_ACK          WebSocketFrameType = 3 // 确认
	WebSocketFrameType_WS_FRAME_ERROR        WebSocketFrameType = 4 // 错误
	WebSocketFrameType_WS_FRAME_CONTROL      WebSocketFrameType = 5 // 控制消息
)

// Enum value maps for WebSocketFrameType.
var (
	WebSocketFrameType_name = map[int32]string{
		0: "WS_FRAME_UNSPECIFIED",
		1: "WS_FRAME_NOTIFICATION",
		2: "WS_FRAME_HEARTBEAT",
		3: "WS_FRAME_ACK",
		4: "WS_FRAME_ERROR",
		5: "WS_FRAME_CONTROL",
	}
	WebSocketFrameType_value = map[string]int32{
		"WS_FRAME_UNSPECIFIED":  0,
		"WS_FRAME_NOTIFICATION": 1,
		"WS_FRAME_HEARTBEAT":    2,
		"WS_FRAME_ACK":          3,
		"WS_FRAME_ERROR":        4,
		"WS_FRAME_CONTROL":      5,
	}
)

func (x WebSocketFrameType) Enum() *WebSocketFrameType {
	p := new(WebSocketFrameType)
	*p = x
	return p
}

func (x WebSocketFrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebSocketFrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_notifier_v1_notifier_types_proto_enumTypes[17].Descriptor()
}

func (WebSocketFrameType) Type() protoreflect.EnumType {
	return &file_notifier_v1_notifier_types_proto_enumTypes[17]
}

func (x WebSocketFrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebSocketFrameType.Descriptor instead.
func (WebSocketFrameType) EnumDescriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{17}
}

// 流控制动作
type StreamAction int32

const (
	StreamAction_STREAM_ACTION_UNSPECIFIED StreamAction = 0
	StreamAction_STREAM_ACTION_START       StreamAction = 1 // 开始-【心跳】
	StreamAction_STREAM_ACTION_PAUSE       StreamAction = 2 // 暂停
	StreamAction_STREAM_ACTION_RESUME      StreamAction = 3 // 恢复
	StreamAction_STREAM_ACTION_STOP        StreamAction = 4 // 停止
)

// Enum value maps for StreamAction.
var (
	StreamAction_name = map[int32]string{
		0: "STREAM_ACTION_UNSPECIFIED",
		1: "STREAM_ACTION_START",
		2: "STREAM_ACTION_PAUSE",
		3: "STREAM_ACTION_RESUME",
		4: "STREAM_ACTION_STOP",
	}
	StreamAction_value = map[string]int32{
		"STREAM_ACTION_UNSPECIFIED": 0,
		"STREAM_ACTION_START":       1,
		"STREAM_ACTION_PAUSE":       2,
		"STREAM_ACTION_RESUME":      3,
		"STREAM_ACTION_STOP":        4,
	}
)

func (x StreamAction) Enum() *StreamAction {
	p := new(StreamAction)
	*p = x
	return p
}

func (x StreamAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamAction) Descriptor() protoreflect.EnumDescriptor {
	return file_notifier_v1_notifier_types_proto_enumTypes[18].Descriptor()
}

func (StreamAction) Type() protoreflect.EnumType {
	return &file_notifier_v1_notifier_types_proto_enumTypes[18]
}

func (x StreamAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamAction.Descriptor instead.
func (StreamAction) EnumDescriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{18}
}

// 认证类型
type AuthType int32

const (
	AuthType_AUTH_TYPE_UNSPECIFIED AuthType = 0
	AuthType_AUTH_TYPE_NONE        AuthType = 1 // 无需认证
	AuthType_AUTH_TYPE_TOKEN       AuthType = 2 // Token认证
	AuthType_AUTH_TYPE_SIGNATURE   AuthType = 3 // 签名认证
	AuthType_AUTH_TYPE_OAUTH       AuthType = 4 // OAuth认证
)

// Enum value maps for AuthType.
var (
	AuthType_name = map[int32]string{
		0: "AUTH_TYPE_UNSPECIFIED",
		1: "AUTH_TYPE_NONE",
		2: "AUTH_TYPE_TOKEN",
		3: "AUTH_TYPE_SIGNATURE",
		4: "AUTH_TYPE_OAUTH",
	}
	AuthType_value = map[string]int32{
		"AUTH_TYPE_UNSPECIFIED": 0,
		"AUTH_TYPE_NONE":        1,
		"AUTH_TYPE_TOKEN":       2,
		"AUTH_TYPE_SIGNATURE":   3,
		"AUTH_TYPE_OAUTH":       4,
	}
)

func (x AuthType) Enum() *AuthType {
	p := new(AuthType)
	*p = x
	return p
}

func (x AuthType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthType) Descriptor() protoreflect.EnumDescriptor {
	return file_notifier_v1_notifier_types_proto_enumTypes[19].Descriptor()
}

func (AuthType) Type() protoreflect.EnumType {
	return &file_notifier_v1_notifier_types_proto_enumTypes[19]
}

func (x AuthType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthType.Descriptor instead.
func (AuthType) EnumDescriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{19}
}

// RobotConfig 通用机器人配置
type RobotConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 目标配置
	ChannelId string   `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"` // 频道/群组ID（Slack, Teams需要）
	ChatId    string   `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`          // 聊天ID（Telegram需要）
	UserIds   []string `protobuf:"bytes,3,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`       // 用户ID列表（私聊或指定接收人）
	// 消息配置
	MentionAll   bool     `protobuf:"varint,4,opt,name=mention_all,json=mentionAll,proto3" json:"mention_all,omitempty"`      // @所有人
	MentionUsers []string `protobuf:"bytes,5,rep,name=mention_users,json=mentionUsers,proto3" json:"mention_users,omitempty"` // @特定用户（用户ID或用户名）
	// 显示配置
	DisplayName string `protobuf:"bytes,6,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // 机器人显示名称
	AvatarUrl   string `protobuf:"bytes,7,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`       // 机器人头像URL
	Color       string `protobuf:"bytes,8,opt,name=color,proto3" json:"color,omitempty"`                                // 消息颜色（如 #FF0000）
	// 格式配置
	MessageFormat string `protobuf:"bytes,9,opt,name=message_format,json=messageFormat,proto3" json:"message_format,omitempty"` // 消息格式: markdown, html, text
	EnableCard    bool   `protobuf:"varint,10,opt,name=enable_card,json=enableCard,proto3" json:"enable_card,omitempty"`        // 是否使用卡片消息
	// 交互配置
	Buttons []*RobotButton `protobuf:"bytes,11,rep,name=buttons,proto3" json:"buttons,omitempty"` // 按钮配置
	// 特定平台配置
	SlackConfig    *SlackConfig    `protobuf:"bytes,20,opt,name=slack_config,json=slackConfig,proto3" json:"slack_config,omitempty"`
	LarkConfig     *LarkConfig     `protobuf:"bytes,21,opt,name=lark_config,json=larkConfig,proto3" json:"lark_config,omitempty"`
	TeamsConfig    *TeamsConfig    `protobuf:"bytes,22,opt,name=teams_config,json=teamsConfig,proto3" json:"teams_config,omitempty"`
	TelegramConfig *TelegramConfig `protobuf:"bytes,23,opt,name=telegram_config,json=telegramConfig,proto3" json:"telegram_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RobotConfig) Reset() {
	*x = RobotConfig{}
	mi := &file_notifier_v1_notifier_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotConfig) ProtoMessage() {}

func (x *RobotConfig) ProtoReflect() protoreflect.Message {
	mi := &file_notifier_v1_notifier_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotConfig.ProtoReflect.Descriptor instead.
func (*RobotConfig) Descriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{0}
}

func (x *RobotConfig) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *RobotConfig) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *RobotConfig) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *RobotConfig) GetMentionAll() bool {
	if x != nil {
		return x.MentionAll
	}
	return false
}

func (x *RobotConfig) GetMentionUsers() []string {
	if x != nil {
		return x.MentionUsers
	}
	return nil
}

func (x *RobotConfig) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *RobotConfig) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *RobotConfig) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *RobotConfig) GetMessageFormat() string {
	if x != nil {
		return x.MessageFormat
	}
	return ""
}

func (x *RobotConfig) GetEnableCard() bool {
	if x != nil {
		return x.EnableCard
	}
	return false
}

func (x *RobotConfig) GetButtons() []*RobotButton {
	if x != nil {
		return x.Buttons
	}
	return nil
}

func (x *RobotConfig) GetSlackConfig() *SlackConfig {
	if x != nil {
		return x.SlackConfig
	}
	return nil
}

func (x *RobotConfig) GetLarkConfig() *LarkConfig {
	if x != nil {
		return x.LarkConfig
	}
	return nil
}

func (x *RobotConfig) GetTeamsConfig() *TeamsConfig {
	if x != nil {
		return x.TeamsConfig
	}
	return nil
}

func (x *RobotConfig) GetTelegramConfig() *TelegramConfig {
	if x != nil {
		return x.TelegramConfig
	}
	return nil
}

// RobotButton 机器人按钮配置
type RobotButton struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`                                      // 点击跳转URL
	Action        ButtonAction           `protobuf:"varint,4,opt,name=action,proto3,enum=notifier.v1.ButtonAction" json:"action,omitempty"` // 动作类型: url, callback
	Style         ButtonStyle            `protobuf:"varint,5,opt,name=style,proto3,enum=notifier.v1.ButtonStyle" json:"style,omitempty"`    // 按钮样式: default, primary, danger
	Value         string                 `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`                                  // 回调值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotButton) Reset() {
	*x = RobotButton{}
	mi := &file_notifier_v1_notifier_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotButton) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotButton) ProtoMessage() {}

func (x *RobotButton) ProtoReflect() protoreflect.Message {
	mi := &file_notifier_v1_notifier_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotButton.ProtoReflect.Descriptor instead.
func (*RobotButton) Descriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{1}
}

func (x *RobotButton) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RobotButton) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *RobotButton) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RobotButton) GetAction() ButtonAction {
	if x != nil {
		return x.Action
	}
	return ButtonAction_BUTTON_ACTION_UNSPECIFIED
}

func (x *RobotButton) GetStyle() ButtonStyle {
	if x != nil {
		return x.Style
	}
	return ButtonStyle_BUTTON_STYLE_UNSPECIFIED
}

func (x *RobotButton) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// SlackConfig Slack特定配置
type SlackConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadTs      string                 `protobuf:"bytes,1,opt,name=thread_ts,json=threadTs,proto3" json:"thread_ts,omitempty"`       // 线程时间戳（用于回复）
	IconEmoji     string                 `protobuf:"bytes,2,opt,name=icon_emoji,json=iconEmoji,proto3" json:"icon_emoji,omitempty"`    // 图标emoji
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`                       // 用户名覆盖
	Attachments   bool                   `protobuf:"varint,4,opt,name=attachments,proto3" json:"attachments,omitempty"`                // 是否使用附件格式
	Blocks        bool                   `protobuf:"varint,5,opt,name=blocks,proto3" json:"blocks,omitempty"`                          // 是否使用Block Kit
	Ephemeral     bool                   `protobuf:"varint,6,opt,name=ephemeral,proto3" json:"ephemeral,omitempty"`                    // 是否为临时消息
	UserGroups    []string               `protobuf:"bytes,7,rep,name=user_groups,json=userGroups,proto3" json:"user_groups,omitempty"` // 用户组ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlackConfig) Reset() {
	*x = SlackConfig{}
	mi := &file_notifier_v1_notifier_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlackConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlackConfig) ProtoMessage() {}

func (x *SlackConfig) ProtoReflect() protoreflect.Message {
	mi := &file_notifier_v1_notifier_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlackConfig.ProtoReflect.Descriptor instead.
func (*SlackConfig) Descriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{2}
}

func (x *SlackConfig) GetThreadTs() string {
	if x != nil {
		return x.ThreadTs
	}
	return ""
}

func (x *SlackConfig) GetIconEmoji() string {
	if x != nil {
		return x.IconEmoji
	}
	return ""
}

func (x *SlackConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SlackConfig) GetAttachments() bool {
	if x != nil {
		return x.Attachments
	}
	return false
}

func (x *SlackConfig) GetBlocks() bool {
	if x != nil {
		return x.Blocks
	}
	return false
}

func (x *SlackConfig) GetEphemeral() bool {
	if x != nil {
		return x.Ephemeral
	}
	return false
}

func (x *SlackConfig) GetUserGroups() []string {
	if x != nil {
		return x.UserGroups
	}
	return nil
}

// LarkConfig 飞书特定配置
type LarkConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgType       string                 `protobuf:"bytes,1,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`              // 消息类型: text, post, card, interactive
	SignType      string                 `protobuf:"bytes,2,opt,name=sign_type,json=signType,proto3" json:"sign_type,omitempty"`           // 签名类型: v1, v2
	UpdateMulti   bool                   `protobuf:"varint,3,opt,name=update_multi,json=updateMulti,proto3" json:"update_multi,omitempty"` // 是否更新多条消息
	CardConfig    *LarkCardConfig        `protobuf:"bytes,4,opt,name=card_config,json=cardConfig,proto3" json:"card_config,omitempty"`     // 卡片配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LarkConfig) Reset() {
	*x = LarkConfig{}
	mi := &file_notifier_v1_notifier_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LarkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LarkConfig) ProtoMessage() {}

func (x *LarkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_notifier_v1_notifier_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LarkConfig.ProtoReflect.Descriptor instead.
func (*LarkConfig) Descriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{3}
}

func (x *LarkConfig) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *LarkConfig) GetSignType() string {
	if x != nil {
		return x.SignType
	}
	return ""
}

func (x *LarkConfig) GetUpdateMulti() bool {
	if x != nil {
		return x.UpdateMulti
	}
	return false
}

func (x *LarkConfig) GetCardConfig() *LarkCardConfig {
	if x != nil {
		return x.CardConfig
	}
	return nil
}

// LarkCardConfig 飞书卡片配置
type LarkCardConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WideScreenMode bool                   `protobuf:"varint,1,opt,name=wide_screen_mode,json=wideScreenMode,proto3" json:"wide_screen_mode,omitempty"` // 宽屏模式
	EnableForward  bool                   `protobuf:"varint,2,opt,name=enable_forward,json=enableForward,proto3" json:"enable_forward,omitempty"`      // 允许转发
	UpdateMulti    bool                   `protobuf:"varint,3,opt,name=update_multi,json=updateMulti,proto3" json:"update_multi,omitempty"`            // 更新多条
	ConfigJson     string                 `protobuf:"bytes,4,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`                // 卡片配置JSON
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LarkCardConfig) Reset() {
	*x = LarkCardConfig{}
	mi := &file_notifier_v1_notifier_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LarkCardConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LarkCardConfig) ProtoMessage() {}

func (x *LarkCardConfig) ProtoReflect() protoreflect.Message {
	mi := &file_notifier_v1_notifier_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LarkCardConfig.ProtoReflect.Descriptor instead.
func (*LarkCardConfig) Descriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{4}
}

func (x *LarkCardConfig) GetWideScreenMode() bool {
	if x != nil {
		return x.WideScreenMode
	}
	return false
}

func (x *LarkCardConfig) GetEnableForward() bool {
	if x != nil {
		return x.EnableForward
	}
	return false
}

func (x *LarkCardConfig) GetUpdateMulti() bool {
	if x != nil {
		return x.UpdateMulti
	}
	return false
}

func (x *LarkCardConfig) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

// TeamsConfig Teams特定配置
type TeamsConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Summary         string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`                                         // 摘要
	ThemeColor      string                 `protobuf:"bytes,2,opt,name=theme_color,json=themeColor,proto3" json:"theme_color,omitempty"`                 // 主题颜色
	Sections        bool                   `protobuf:"varint,3,opt,name=sections,proto3" json:"sections,omitempty"`                                      // 是否使用sections
	PotentialAction bool                   `protobuf:"varint,4,opt,name=potential_action,json=potentialAction,proto3" json:"potential_action,omitempty"` // 是否包含操作
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TeamsConfig) Reset() {
	*x = TeamsConfig{}
	mi := &file_notifier_v1_notifier_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamsConfig) ProtoMessage() {}

func (x *TeamsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_notifier_v1_notifier_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamsConfig.ProtoReflect.Descriptor instead.
func (*TeamsConfig) Descriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{5}
}

func (x *TeamsConfig) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *TeamsConfig) GetThemeColor() string {
	if x != nil {
		return x.ThemeColor
	}
	return ""
}

func (x *TeamsConfig) GetSections() bool {
	if x != nil {
		return x.Sections
	}
	return false
}

func (x *TeamsConfig) GetPotentialAction() bool {
	if x != nil {
		return x.PotentialAction
	}
	return false
}

// TelegramConfig Telegram特定配置
type TelegramConfig struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ParseMode             string                 `protobuf:"bytes,1,opt,name=parse_mode,json=parseMode,proto3" json:"parse_mode,omitempty"`                                          // 解析模式: Markdown, HTML
	DisableNotification   bool                   `protobuf:"varint,2,opt,name=disable_notification,json=disableNotification,proto3" json:"disable_notification,omitempty"`           // 静音通知
	ReplyToMessageId      int64                  `protobuf:"varint,3,opt,name=reply_to_message_id,json=replyToMessageId,proto3" json:"reply_to_message_id,omitempty"`                // 回复消息ID
	ReplyMarkup           string                 `protobuf:"bytes,4,opt,name=reply_markup,json=replyMarkup,proto3" json:"reply_markup,omitempty"`                                    // 键盘标记JSON
	DisableWebPagePreview bool                   `protobuf:"varint,5,opt,name=disable_web_page_preview,json=disableWebPagePreview,proto3" json:"disable_web_page_preview,omitempty"` // 禁用链接预览
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TelegramConfig) Reset() {
	*x = TelegramConfig{}
	mi := &file_notifier_v1_notifier_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelegramConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramConfig) ProtoMessage() {}

func (x *TelegramConfig) ProtoReflect() protoreflect.Message {
	mi := &file_notifier_v1_notifier_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramConfig.ProtoReflect.Descriptor instead.
func (*TelegramConfig) Descriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{6}
}

func (x *TelegramConfig) GetParseMode() string {
	if x != nil {
		return x.ParseMode
	}
	return ""
}

func (x *TelegramConfig) GetDisableNotification() bool {
	if x != nil {
		return x.DisableNotification
	}
	return false
}

func (x *TelegramConfig) GetReplyToMessageId() int64 {
	if x != nil {
		return x.ReplyToMessageId
	}
	return 0
}

func (x *TelegramConfig) GetReplyMarkup() string {
	if x != nil {
		return x.ReplyMarkup
	}
	return ""
}

func (x *TelegramConfig) GetDisableWebPagePreview() bool {
	if x != nil {
		return x.DisableWebPagePreview
	}
	return false
}

// 无认证
type NoneAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoneAuth) Reset() {
	*x = NoneAuth{}
	mi := &file_notifier_v1_notifier_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoneAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoneAuth) ProtoMessage() {}

func (x *NoneAuth) ProtoReflect() protoreflect.Message {
	mi := &file_notifier_v1_notifier_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoneAuth.ProtoReflect.Descriptor instead.
func (*NoneAuth) Descriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{7}
}

// Token认证
type TokenAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                          // Token值
	TokenType     string                 `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"` // Token类型: Bearer, Basic
	Header        string                 `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`                        // Header名称，默认 Authorization
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenAuth) Reset() {
	*x = TokenAuth{}
	mi := &file_notifier_v1_notifier_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenAuth) ProtoMessage() {}

func (x *TokenAuth) ProtoReflect() protoreflect.Message {
	mi := &file_notifier_v1_notifier_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenAuth.ProtoReflect.Descriptor instead.
func (*TokenAuth) Descriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{8}
}

func (x *TokenAuth) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenAuth) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *TokenAuth) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

// 签名认证
type SignatureAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`       // 签名密钥
	Algorithm     string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"` // 签名算法: HMAC-SHA256, HMAC-SHA1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignatureAuth) Reset() {
	*x = SignatureAuth{}
	mi := &file_notifier_v1_notifier_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignatureAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureAuth) ProtoMessage() {}

func (x *SignatureAuth) ProtoReflect() protoreflect.Message {
	mi := &file_notifier_v1_notifier_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureAuth.ProtoReflect.Descriptor instead.
func (*SignatureAuth) Descriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{9}
}

func (x *SignatureAuth) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *SignatureAuth) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

// OAuth认证
type OAuthAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`             // 客户端ID
	ClientSecret  string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"` // 客户端密钥
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`    // 访问令牌
	RefreshToken  string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"` // 刷新令牌
	TokenUrl      string                 `protobuf:"bytes,5,opt,name=token_url,json=tokenUrl,proto3" json:"token_url,omitempty"`             // 令牌URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuthAuth) Reset() {
	*x = OAuthAuth{}
	mi := &file_notifier_v1_notifier_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthAuth) ProtoMessage() {}

func (x *OAuthAuth) ProtoReflect() protoreflect.Message {
	mi := &file_notifier_v1_notifier_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthAuth.ProtoReflect.Descriptor instead.
func (*OAuthAuth) Descriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_types_proto_rawDescGZIP(), []int{10}
}

func (x *OAuthAuth) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OAuthAuth) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *OAuthAuth) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *OAuthAuth) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *OAuthAuth) GetTokenUrl() string {
	if x != nil {
		return x.TokenUrl
	}
	return ""
}

var File_notifier_v1_notifier_types_proto protoreflect.FileDescriptor

const file_notifier_v1_notifier_types_proto_rawDesc = "" +
	"\n" +
	" notifier/v1/notifier_types.proto\x12\vnotifier.v1\"\xf4\x04\n" +
	"\vRobotConfig\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x19\n" +
	"\buser_ids\x18\x03 \x03(\tR\auserIds\x12\x1f\n" +
	"\vmention_all\x18\x04 \x01(\bR\n" +
	"mentionAll\x12#\n" +
	"\rmention_users\x18\x05 \x03(\tR\fmentionUsers\x12!\n" +
	"\fdisplay_name\x18\x06 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\a \x01(\tR\tavatarUrl\x12\x14\n" +
	"\x05color\x18\b \x01(\tR\x05color\x12%\n" +
	"\x0emessage_format\x18\t \x01(\tR\rmessageFormat\x12\x1f\n" +
	"\venable_card\x18\n" +
	" \x01(\bR\n" +
	"enableCard\x122\n" +
	"\abuttons\x18\v \x03(\v2\x18.notifier.v1.RobotButtonR\abuttons\x12;\n" +
	"\fslack_config\x18\x14 \x01(\v2\x18.notifier.v1.SlackConfigR\vslackConfig\x128\n" +
	"\vlark_config\x18\x15 \x01(\v2\x17.notifier.v1.LarkConfigR\n" +
	"larkConfig\x12;\n" +
	"\fteams_config\x18\x16 \x01(\v2\x18.notifier.v1.TeamsConfigR\vteamsConfig\x12D\n" +
	"\x0ftelegram_config\x18\x17 \x01(\v2\x1b.notifier.v1.TelegramConfigR\x0etelegramConfig\"\xbc\x01\n" +
	"\vRobotButton\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x121\n" +
	"\x06action\x18\x04 \x01(\x0e2\x19.notifier.v1.ButtonActionR\x06action\x12.\n" +
	"\x05style\x18\x05 \x01(\x0e2\x18.notifier.v1.ButtonStyleR\x05style\x12\x14\n" +
	"\x05value\x18\x06 \x01(\tR\x05value\"\xde\x01\n" +
	"\vSlackConfig\x12\x1b\n" +
	"\tthread_ts\x18\x01 \x01(\tR\bthreadTs\x12\x1d\n" +
	"\n" +
	"icon_emoji\x18\x02 \x01(\tR\ticonEmoji\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12 \n" +
	"\vattachments\x18\x04 \x01(\bR\vattachments\x12\x16\n" +
	"\x06blocks\x18\x05 \x01(\bR\x06blocks\x12\x1c\n" +
	"\tephemeral\x18\x06 \x01(\bR\tephemeral\x12\x1f\n" +
	"\vuser_groups\x18\a \x03(\tR\n" +
	"userGroups\"\xa5\x01\n" +
	"\n" +
	"LarkConfig\x12\x19\n" +
	"\bmsg_type\x18\x01 \x01(\tR\amsgType\x12\x1b\n" +
	"\tsign_type\x18\x02 \x01(\tR\bsignType\x12!\n" +
	"\fupdate_multi\x18\x03 \x01(\bR\vupdateMulti\x12<\n" +
	"\vcard_config\x18\x04 \x01(\v2\x1b.notifier.v1.LarkCardConfigR\n" +
	"cardConfig\"\xa5\x01\n" +
	"\x0eLarkCardConfig\x12(\n" +
	"\x10wide_screen_mode\x18\x01 \x01(\bR\x0ewideScreenMode\x12%\n" +
	"\x0eenable_forward\x18\x02 \x01(\bR\renableForward\x12!\n" +
	"\fupdate_multi\x18\x03 \x01(\bR\vupdateMulti\x12\x1f\n" +
	"\vconfig_json\x18\x04 \x01(\tR\n" +
	"configJson\"\x8f\x01\n" +
	"\vTeamsConfig\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12\x1f\n" +
	"\vtheme_color\x18\x02 \x01(\tR\n" +
	"themeColor\x12\x1a\n" +
	"\bsections\x18\x03 \x01(\bR\bsections\x12)\n" +
	"\x10potential_action\x18\x04 \x01(\bR\x0fpotentialAction\"\xed\x01\n" +
	"\x0eTelegramConfig\x12\x1d\n" +
	"\n" +
	"parse_mode\x18\x01 \x01(\tR\tparseMode\x121\n" +
	"\x14disable_notification\x18\x02 \x01(\bR\x13disableNotification\x12-\n" +
	"\x13reply_to_message_id\x18\x03 \x01(\x03R\x10replyToMessageId\x12!\n" +
	"\freply_markup\x18\x04 \x01(\tR\vreplyMarkup\x127\n" +
	"\x18disable_web_page_preview\x18\x05 \x01(\bR\x15disableWebPagePreview\"\n" +
	"\n" +
	"\bNoneAuth\"X\n" +
	"\tTokenAuth\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\x12\x16\n" +
	"\x06header\x18\x03 \x01(\tR\x06header\"E\n" +
	"\rSignatureAuth\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\"\xb2\x01\n" +
	"\tOAuthAuth\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x02 \x01(\tR\fclientSecret\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x12\x1b\n" +
	"\ttoken_url\x18\x05 \x01(\tR\btokenUrl*\xed\x04\n" +
	"\x11NotifierErrorCode\x12#\n" +
	"\x1fNOTIFIER_ERROR_CODE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1bNOTIFIER_ERROR_CODE_SUCCESS\x10\xc8\x01\x12$\n" +
	"\x1fNOTIFIER_ERROR_CODE_BAD_REQUEST\x10\x90\x03\x12%\n" +
	" NOTIFIER_ERROR_CODE_UNAUTHORIZED\x10\x91\x03\x12\"\n" +
	"\x1dNOTIFIER_ERROR_CODE_FORBIDDEN\x10\x93\x03\x12\"\n" +
	"\x1dNOTIFIER_ERROR_CODE_NOT_FOUND\x10\x94\x03\x12!\n" +
	"\x1cNOTIFIER_ERROR_CODE_CONFLICT\x10\x99\x03\x12*\n" +
	"%NOTIFIER_ERROR_CODE_TOO_MANY_REQUESTS\x10\xad\x03\x12.\n" +
	")NOTIFIER_ERROR_CODE_INTERNAL_SERVER_ERROR\x10\xf4\x03\x12 \n" +
	"\x1bNOTIFIER_ERROR_CODE_TIMEOUT\x10\xf8\x03\x12,\n" +
	"'NOTIFIER_ERROR_CODE_SERVICE_UNAVAILABLE\x10\xf7\x03\x12(\n" +
	"#NOTIFIER_ERROR_CODE_ENDPOINT_FAILED\x10\xfe\x03\x12*\n" +
	"%NOTIFIER_ERROR_CODE_MERCHANT_DISABLED\x10\xd8\x04\x12+\n" +
	"&NOTIFIER_ERROR_CODE_SUBSCRIPTION_LIMIT\x10\xbc\x05\x12*\n" +
	"%NOTIFIER_ERROR_CODE_SIGNATURE_INVALID\x10\xa0\x06*\x8a\x01\n" +
	"\x0eMerchantStatus\x12\x1f\n" +
	"\x1bMERCHANT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16MERCHANT_STATUS_ACTIVE\x10\x01\x12\x1d\n" +
	"\x19MERCHANT_STATUS_SUSPENDED\x10\x02\x12\x1c\n" +
	"\x18MERCHANT_STATUS_DISABLED\x10\x03*t\n" +
	"\vPushChannel\x12\x17\n" +
	"\x13CHANNEL_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fCHANNEL_HTTP\x10\x01\x12\x15\n" +
	"\x11CHANNEL_WEBSOCKET\x10\x02\x12\x10\n" +
	"\fCHANNEL_GRPC\x10\x03\x12\x11\n" +
	"\rCHANNEL_ROBOT\x10\x04*\x8a\x01\n" +
	"\n" +
	"PushStatus\x12\x1b\n" +
	"\x17PUSH_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PUSH_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13PUSH_STATUS_SUCCESS\x10\x02\x12\x16\n" +
	"\x12PUSH_STATUS_FAILED\x10\x03\x12\x15\n" +
	"\x11PUSH_STATUS_RETRY\x10\x04*\x81\x01\n" +
	"\x14NotificationPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x01\x12\x13\n" +
	"\x0fPRIORITY_NORMAL\x10\x02\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x03\x12\x15\n" +
	"\x11PRIORITY_CRITICAL\x10\x04*\x80\x01\n" +
	"\x14NotificationCategory\x12\x18\n" +
	"\x14CATEGORY_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCATEGORY_SYSTEM\x10\x01\x12\x11\n" +
	"\rCATEGORY_RISK\x10\x02\x12\x11\n" +
	"\rCATEGORY_GAME\x10\x03\x12\x13\n" +
	"\x0fCATEGORY_REPORT\x10\x04*\xfa\x03\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dEVENT_TYPE_SYSTEM_MAINTENANCE\x10e\x12\"\n" +
	"\x1eEVENT_TYPE_SYSTEM_ANNOUNCEMENT\x10f\x12\x1d\n" +
	"\x19EVENT_TYPE_SYSTEM_UPGRADE\x10g\x12\x1b\n" +
	"\x17EVENT_TYPE_SYSTEM_ERROR\x10h\x12\x1a\n" +
	"\x15EVENT_TYPE_RISK_ALERT\x10\xc9\x01\x12\x18\n" +
	"\x13EVENT_TYPE_BAD_DEBT\x10\xca\x01\x12\x1e\n" +
	"\x19EVENT_TYPE_FRAUD_DETECTED\x10\xcb\x01\x12!\n" +
	"\x1cEVENT_TYPE_ABNORMAL_BEHAVIOR\x10\xcc\x01\x12\x1b\n" +
	"\x16EVENT_TYPE_GAME_RESULT\x10\xad\x02\x12\x1c\n" +
	"\x17EVENT_TYPE_GAME_BIG_WIN\x10\xae\x02\x12\x1c\n" +
	"\x17EVENT_TYPE_DAILY_REPORT\x10\x91\x03\x12\x1d\n" +
	"\x18EVENT_TYPE_WEEKLY_REPORT\x10\x92\x03\x12\x1e\n" +
	"\x19EVENT_TYPE_MONTHLY_REPORT\x10\x93\x03\x12\x1e\n" +
	"\x19EVENT_TYPE_ANOMALY_REPORT\x10\x94\x03\x12\x1d\n" +
	"\x18EVENT_TYPE_CUSTOM_REPORT\x10\x95\x03*\x80\x01\n" +
	"\tRiskLevel\x12\x1a\n" +
	"\x16RISK_LEVEL_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eRISK_LEVEL_LOW\x10\x01\x12\x15\n" +
	"\x11RISK_LEVEL_MEDIUM\x10\x02\x12\x13\n" +
	"\x0fRISK_LEVEL_HIGH\x10\x03\x12\x17\n" +
	"\x13RISK_LEVEL_CRITICAL\x10\x04*\xa5\x01\n" +
	"\bRiskType\x12\x19\n" +
	"\x15RISK_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fRISK_TYPE_FRAUD\x10\x01\x12\x16\n" +
	"\x12RISK_TYPE_ABNORMAL\x10\x02\x12\x18\n" +
	"\x14RISK_TYPE_SUSPICIOUS\x10\x03\x12\x17\n" +
	"\x13RISK_TYPE_BLACKLIST\x10\x04\x12\x1e\n" +
	"\x1aRISK_TYPE_MONEY_LAUNDERING\x10\x05*\x91\x01\n" +
	"\x0fMaintenanceType\x12 \n" +
	"\x1cMAINTENANCE_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aMAINTENANCE_TYPE_SCHEDULED\x10\x01\x12\x1e\n" +
	"\x1aMAINTENANCE_TYPE_EMERGENCY\x10\x02\x12\x1c\n" +
	"\x18MAINTENANCE_TYPE_UPGRADE\x10\x03*\x90\x01\n" +
	"\x10AnnouncementType\x12!\n" +
	"\x1dANNOUNCEMENT_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ANNOUNCEMENT_TYPE_INFO\x10\x01\x12\x1d\n" +
	"\x19ANNOUNCEMENT_TYPE_WARNING\x10\x02\x12\x1e\n" +
	"\x1aANNOUNCEMENT_TYPE_CRITICAL\x10\x03*\x96\x01\n" +
	"\x10GameRecordStatus\x12\x1b\n" +
	"\x17GAME_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13GAME_STATUS_BETTING\x10\x01\x12\x17\n" +
	"\x13GAME_STATUS_SETTLED\x10\x02\x12\x19\n" +
	"\x15GAME_STATUS_CANCELLED\x10\x03\x12\x18\n" +
	"\x14GAME_STATUS_ADJUSTED\x10\x04*\xc9\x01\n" +
	"\vAnomalyType\x12\x1c\n" +
	"\x18ANOMALY_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ANOMALY_TYPE_TRAFFIC\x10\x01\x12\x18\n" +
	"\x14ANOMALY_TYPE_REVENUE\x10\x02\x12\x1e\n" +
	"\x1aANOMALY_TYPE_USER_BEHAVIOR\x10\x03\x12\x17\n" +
	"\x13ANOMALY_TYPE_SYSTEM\x10\x04\x12\x18\n" +
	"\x14ANOMALY_TYPE_PAYMENT\x10\x05\x12\x15\n" +
	"\x11ANOMALY_TYPE_GAME\x10\x06*\x81\x01\n" +
	"\tRobotType\x12\x1a\n" +
	"\x16ROBOT_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ROBOT_TYPE_SLACK\x10\x01\x12\x13\n" +
	"\x0fROBOT_TYPE_LARK\x10\x02\x12\x14\n" +
	"\x10ROBOT_TYPE_TEAMS\x10\x03\x12\x17\n" +
	"\x13ROBOT_TYPE_TELEGRAM\x10\x04*\x80\x01\n" +
	"\x0eAttachmentType\x12\x1f\n" +
	"\x1bATTACHMENT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ATTACHMENT_TYPE_IMAGE\x10\x01\x12\x18\n" +
	"\x14ATTACHMENT_TYPE_FILE\x10\x02\x12\x18\n" +
	"\x14ATTACHMENT_TYPE_LINK\x10\x03*{\n" +
	"\fButtonAction\x12\x1d\n" +
	"\x19BUTTON_ACTION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11BUTTON_ACTION_URL\x10\x01\x12\x1a\n" +
	"\x16BUTTON_ACTION_CALLBACK\x10\x02\x12\x19\n" +
	"\x15BUTTON_ACTION_COMMAND\x10\x03*\xac\x01\n" +
	"\vButtonStyle\x12\x1c\n" +
	"\x18BUTTON_STYLE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14BUTTON_STYLE_DEFAULT\x10\x01\x12\x18\n" +
	"\x14BUTTON_STYLE_PRIMARY\x10\x02\x12\x18\n" +
	"\x14BUTTON_STYLE_SUCCESS\x10\x03\x12\x17\n" +
	"\x13BUTTON_STYLE_DANGER\x10\x04\x12\x18\n" +
	"\x14BUTTON_STYLE_WARNING\x10\x05*\x9d\x01\n" +
	"\x12WebSocketFrameType\x12\x18\n" +
	"\x14WS_FRAME_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15WS_FRAME_NOTIFICATION\x10\x01\x12\x16\n" +
	"\x12WS_FRAME_HEARTBEAT\x10\x02\x12\x10\n" +
	"\fWS_FRAME_ACK\x10\x03\x12\x12\n" +
	"\x0eWS_FRAME_ERROR\x10\x04\x12\x14\n" +
	"\x10WS_FRAME_CONTROL\x10\x05*\x91\x01\n" +
	"\fStreamAction\x12\x1d\n" +
	"\x19STREAM_ACTION_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13STREAM_ACTION_START\x10\x01\x12\x17\n" +
	"\x13STREAM_ACTION_PAUSE\x10\x02\x12\x18\n" +
	"\x14STREAM_ACTION_RESUME\x10\x03\x12\x16\n" +
	"\x12STREAM_ACTION_STOP\x10\x04*|\n" +
	"\bAuthType\x12\x19\n" +
	"\x15AUTH_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eAUTH_TYPE_NONE\x10\x01\x12\x13\n" +
	"\x0fAUTH_TYPE_TOKEN\x10\x02\x12\x17\n" +
	"\x13AUTH_TYPE_SIGNATURE\x10\x03\x12\x13\n" +
	"\x0fAUTH_TYPE_OAUTH\x10\x04B8Z6github.com/og-game/game-proto/proto-gen-go/notifier/v1b\x06proto3"

var (
	file_notifier_v1_notifier_types_proto_rawDescOnce sync.Once
	file_notifier_v1_notifier_types_proto_rawDescData []byte
)

func file_notifier_v1_notifier_types_proto_rawDescGZIP() []byte {
	file_notifier_v1_notifier_types_proto_rawDescOnce.Do(func() {
		file_notifier_v1_notifier_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notifier_v1_notifier_types_proto_rawDesc), len(file_notifier_v1_notifier_types_proto_rawDesc)))
	})
	return file_notifier_v1_notifier_types_proto_rawDescData
}

var file_notifier_v1_notifier_types_proto_enumTypes = make([]protoimpl.EnumInfo, 20)
var file_notifier_v1_notifier_types_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_notifier_v1_notifier_types_proto_goTypes = []any{
	(NotifierErrorCode)(0),    // 0: notifier.v1.NotifierErrorCode
	(MerchantStatus)(0),       // 1: notifier.v1.MerchantStatus
	(PushChannel)(0),          // 2: notifier.v1.PushChannel
	(PushStatus)(0),           // 3: notifier.v1.PushStatus
	(NotificationPriority)(0), // 4: notifier.v1.NotificationPriority
	(NotificationCategory)(0), // 5: notifier.v1.NotificationCategory
	(EventType)(0),            // 6: notifier.v1.EventType
	(RiskLevel)(0),            // 7: notifier.v1.RiskLevel
	(RiskType)(0),             // 8: notifier.v1.RiskType
	(MaintenanceType)(0),      // 9: notifier.v1.MaintenanceType
	(AnnouncementType)(0),     // 10: notifier.v1.AnnouncementType
	(GameRecordStatus)(0),     // 11: notifier.v1.GameRecordStatus
	(AnomalyType)(0),          // 12: notifier.v1.AnomalyType
	(RobotType)(0),            // 13: notifier.v1.RobotType
	(AttachmentType)(0),       // 14: notifier.v1.AttachmentType
	(ButtonAction)(0),         // 15: notifier.v1.ButtonAction
	(ButtonStyle)(0),          // 16: notifier.v1.ButtonStyle
	(WebSocketFrameType)(0),   // 17: notifier.v1.WebSocketFrameType
	(StreamAction)(0),         // 18: notifier.v1.StreamAction
	(AuthType)(0),             // 19: notifier.v1.AuthType
	(*RobotConfig)(nil),       // 20: notifier.v1.RobotConfig
	(*RobotButton)(nil),       // 21: notifier.v1.RobotButton
	(*SlackConfig)(nil),       // 22: notifier.v1.SlackConfig
	(*LarkConfig)(nil),        // 23: notifier.v1.LarkConfig
	(*LarkCardConfig)(nil),    // 24: notifier.v1.LarkCardConfig
	(*TeamsConfig)(nil),       // 25: notifier.v1.TeamsConfig
	(*TelegramConfig)(nil),    // 26: notifier.v1.TelegramConfig
	(*NoneAuth)(nil),          // 27: notifier.v1.NoneAuth
	(*TokenAuth)(nil),         // 28: notifier.v1.TokenAuth
	(*SignatureAuth)(nil),     // 29: notifier.v1.SignatureAuth
	(*OAuthAuth)(nil),         // 30: notifier.v1.OAuthAuth
}
var file_notifier_v1_notifier_types_proto_depIdxs = []int32{
	21, // 0: notifier.v1.RobotConfig.buttons:type_name -> notifier.v1.RobotButton
	22, // 1: notifier.v1.RobotConfig.slack_config:type_name -> notifier.v1.SlackConfig
	23, // 2: notifier.v1.RobotConfig.lark_config:type_name -> notifier.v1.LarkConfig
	25, // 3: notifier.v1.RobotConfig.teams_config:type_name -> notifier.v1.TeamsConfig
	26, // 4: notifier.v1.RobotConfig.telegram_config:type_name -> notifier.v1.TelegramConfig
	15, // 5: notifier.v1.RobotButton.action:type_name -> notifier.v1.ButtonAction
	16, // 6: notifier.v1.RobotButton.style:type_name -> notifier.v1.ButtonStyle
	24, // 7: notifier.v1.LarkConfig.card_config:type_name -> notifier.v1.LarkCardConfig
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_notifier_v1_notifier_types_proto_init() }
func file_notifier_v1_notifier_types_proto_init() {
	if File_notifier_v1_notifier_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notifier_v1_notifier_types_proto_rawDesc), len(file_notifier_v1_notifier_types_proto_rawDesc)),
			NumEnums:      20,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notifier_v1_notifier_types_proto_goTypes,
		DependencyIndexes: file_notifier_v1_notifier_types_proto_depIdxs,
		EnumInfos:         file_notifier_v1_notifier_types_proto_enumTypes,
		MessageInfos:      file_notifier_v1_notifier_types_proto_msgTypes,
	}.Build()
	File_notifier_v1_notifier_types_proto = out.File
	file_notifier_v1_notifier_types_proto_goTypes = nil
	file_notifier_v1_notifier_types_proto_depIdxs = nil
}
