// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: temporal.proto

package searchattributeservice

import (
	"context"

	"github.com/og-game/game-proto/proto-gen-go/temporal/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchConfig                       = v1.BatchConfig
	BatchControlResult                = v1.BatchControlResult
	BatchDeleteResult                 = v1.BatchDeleteResult
	BatchDeleteTarget                 = v1.BatchDeleteTarget
	BatchResult                       = v1.BatchResult
	BatchTarget                       = v1.BatchTarget
	ControlOperationInfo              = v1.ControlOperationInfo
	ControlOptions                    = v1.ControlOptions
	ControlWorkflowData               = v1.ControlWorkflowData
	ControlWorkflowRequest            = v1.ControlWorkflowRequest
	ControlWorkflowResponse           = v1.ControlWorkflowResponse
	DelayOptions                      = v1.DelayOptions
	DeleteOptions                     = v1.DeleteOptions
	DeleteStatistics                  = v1.DeleteStatistics
	DeleteWorkflowData                = v1.DeleteWorkflowData
	DeleteWorkflowRequest             = v1.DeleteWorkflowRequest
	DeleteWorkflowResponse            = v1.DeleteWorkflowResponse
	ExecutionConfig                   = v1.ExecutionConfig
	ExecutionInfo                     = v1.ExecutionInfo
	ListOptions                       = v1.ListOptions
	ListScheduleOptions               = v1.ListScheduleOptions
	ListSchedulesData                 = v1.ListSchedulesData
	ListSchedulesRequest              = v1.ListSchedulesRequest
	ListSchedulesResponse             = v1.ListSchedulesResponse
	ListSearchAttributesData          = v1.ListSearchAttributesData
	ListSearchAttributesRequest       = v1.ListSearchAttributesRequest
	ListSearchAttributesResponse      = v1.ListSearchAttributesResponse
	ListWorkflowsData                 = v1.ListWorkflowsData
	ListWorkflowsRequest              = v1.ListWorkflowsRequest
	ListWorkflowsResponse             = v1.ListWorkflowsResponse
	ManageScheduleData                = v1.ManageScheduleData
	ManageScheduleRequest             = v1.ManageScheduleRequest
	ManageScheduleResponse            = v1.ManageScheduleResponse
	QueryControlOperationData         = v1.QueryControlOperationData
	QueryControlOperationRequest      = v1.QueryControlOperationRequest
	QueryControlOperationResponse     = v1.QueryControlOperationResponse
	QueryDeleteResult                 = v1.QueryDeleteResult
	QueryDeleteTarget                 = v1.QueryDeleteTarget
	QueryOptions                      = v1.QueryOptions
	QueryScheduleRequest              = v1.QueryScheduleRequest
	QueryScheduleResponse             = v1.QueryScheduleResponse
	QuerySearchAttributeUsageData     = v1.QuerySearchAttributeUsageData
	QuerySearchAttributeUsageRequest  = v1.QuerySearchAttributeUsageRequest
	QuerySearchAttributeUsageResponse = v1.QuerySearchAttributeUsageResponse
	QueryWorkflowData                 = v1.QueryWorkflowData
	QueryWorkflowRequest              = v1.QueryWorkflowRequest
	QueryWorkflowResponse             = v1.QueryWorkflowResponse
	QueryWorkflowStateData            = v1.QueryWorkflowStateData
	QueryWorkflowStateRequest         = v1.QueryWorkflowStateRequest
	QueryWorkflowStateResponse        = v1.QueryWorkflowStateResponse
	RegisterSearchAttributesData      = v1.RegisterSearchAttributesData
	RegisterSearchAttributesRequest   = v1.RegisterSearchAttributesRequest
	RegisterSearchAttributesResponse  = v1.RegisterSearchAttributesResponse
	RemoveSearchAttributesData        = v1.RemoveSearchAttributesData
	RemoveSearchAttributesRequest     = v1.RemoveSearchAttributesRequest
	RemoveSearchAttributesResponse    = v1.RemoveSearchAttributesResponse
	ReplaceWorkflowData               = v1.ReplaceWorkflowData
	ReplaceWorkflowRequest            = v1.ReplaceWorkflowRequest
	ReplaceWorkflowResponse           = v1.ReplaceWorkflowResponse
	RetentionPolicy                   = v1.RetentionPolicy
	ScheduleInfo                      = v1.ScheduleInfo
	SchedulePolicy                    = v1.SchedulePolicy
	ScheduleResult                    = v1.ScheduleResult
	ScheduleSpec                      = v1.ScheduleSpec
	SearchAttributeFilter             = v1.SearchAttributeFilter
	SearchAttributeInfo               = v1.SearchAttributeInfo
	SearchAttributeRegistrationResult = v1.SearchAttributeRegistrationResult
	SearchAttributeRemovalResult      = v1.SearchAttributeRemovalResult
	SearchAttributeStats              = v1.SearchAttributeStats
	SearchAttributeUsage              = v1.SearchAttributeUsage
	SearchAttributeValidation         = v1.SearchAttributeValidation
	SignalWithStartData               = v1.SignalWithStartData
	SignalWithStartRequest            = v1.SignalWithStartRequest
	SignalWithStartResponse           = v1.SignalWithStartResponse
	SignalWorkflowData                = v1.SignalWorkflowData
	SignalWorkflowRequest             = v1.SignalWorkflowRequest
	SignalWorkflowResponse            = v1.SignalWorkflowResponse
	SingleDeleteResult                = v1.SingleDeleteResult
	SingleDeleteTarget                = v1.SingleDeleteTarget
	SingleResult                      = v1.SingleResult
	StackFrame                        = v1.StackFrame
	StartWorkflowData                 = v1.StartWorkflowData
	StartWorkflowRequest              = v1.StartWorkflowRequest
	StartWorkflowResponse             = v1.StartWorkflowResponse
	StringList                        = v1.StringList
	UsageQueryOptions                 = v1.UsageQueryOptions
	UsageStats                        = v1.UsageStats
	ValidateSearchAttributesData      = v1.ValidateSearchAttributesData
	ValidateSearchAttributesRequest   = v1.ValidateSearchAttributesRequest
	ValidateSearchAttributesResponse  = v1.ValidateSearchAttributesResponse
	ValidationResult                  = v1.ValidationResult
	ValueDistribution                 = v1.ValueDistribution
	WorkflowAction                    = v1.WorkflowAction
	WorkflowEvent                     = v1.WorkflowEvent
	WorkflowHistory                   = v1.WorkflowHistory
	WorkflowInfo                      = v1.WorkflowInfo
	WorkflowItem                      = v1.WorkflowItem
	WorkflowStackTrace                = v1.WorkflowStackTrace
	WorkflowStatus                    = v1.WorkflowStatus
	WorkflowTarget                    = v1.WorkflowTarget

	SearchAttributeService interface {
		// 注册搜索属性
		RegisterSearchAttributes(ctx context.Context, in *RegisterSearchAttributesRequest, opts ...grpc.CallOption) (*RegisterSearchAttributesResponse, error)
		// 列出搜索属性
		ListSearchAttributes(ctx context.Context, in *ListSearchAttributesRequest, opts ...grpc.CallOption) (*ListSearchAttributesResponse, error)
		// 删除搜索属性（谨慎使用）
		RemoveSearchAttributes(ctx context.Context, in *RemoveSearchAttributesRequest, opts ...grpc.CallOption) (*RemoveSearchAttributesResponse, error)
		// 查询搜索属性使用情况
		QuerySearchAttributeUsage(ctx context.Context, in *QuerySearchAttributeUsageRequest, opts ...grpc.CallOption) (*QuerySearchAttributeUsageResponse, error)
		// 验证搜索属性
		ValidateSearchAttributes(ctx context.Context, in *ValidateSearchAttributesRequest, opts ...grpc.CallOption) (*ValidateSearchAttributesResponse, error)
	}

	defaultSearchAttributeService struct {
		cli zrpc.Client
	}
)

func NewSearchAttributeService(cli zrpc.Client) SearchAttributeService {
	return &defaultSearchAttributeService{
		cli: cli,
	}
}

// 注册搜索属性
func (m *defaultSearchAttributeService) RegisterSearchAttributes(ctx context.Context, in *RegisterSearchAttributesRequest, opts ...grpc.CallOption) (*RegisterSearchAttributesResponse, error) {
	client := v1.NewSearchAttributeServiceClient(m.cli.Conn())
	return client.RegisterSearchAttributes(ctx, in, opts...)
}

// 列出搜索属性
func (m *defaultSearchAttributeService) ListSearchAttributes(ctx context.Context, in *ListSearchAttributesRequest, opts ...grpc.CallOption) (*ListSearchAttributesResponse, error) {
	client := v1.NewSearchAttributeServiceClient(m.cli.Conn())
	return client.ListSearchAttributes(ctx, in, opts...)
}

// 删除搜索属性（谨慎使用）
func (m *defaultSearchAttributeService) RemoveSearchAttributes(ctx context.Context, in *RemoveSearchAttributesRequest, opts ...grpc.CallOption) (*RemoveSearchAttributesResponse, error) {
	client := v1.NewSearchAttributeServiceClient(m.cli.Conn())
	return client.RemoveSearchAttributes(ctx, in, opts...)
}

// 查询搜索属性使用情况
func (m *defaultSearchAttributeService) QuerySearchAttributeUsage(ctx context.Context, in *QuerySearchAttributeUsageRequest, opts ...grpc.CallOption) (*QuerySearchAttributeUsageResponse, error) {
	client := v1.NewSearchAttributeServiceClient(m.cli.Conn())
	return client.QuerySearchAttributeUsage(ctx, in, opts...)
}

// 验证搜索属性
func (m *defaultSearchAttributeService) ValidateSearchAttributes(ctx context.Context, in *ValidateSearchAttributesRequest, opts ...grpc.CallOption) (*ValidateSearchAttributesResponse, error) {
	client := v1.NewSearchAttributeServiceClient(m.cli.Conn())
	return client.ValidateSearchAttributes(ctx, in, opts...)
}
