// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: fund.proto

package fundinnerservice

import (
	"context"

	"github.com/og-game/game-proto/proto-gen-go/fund/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ExecuteTransactionReply  = v1.ExecuteTransactionReply
	ExecuteTransactionReq    = v1.ExecuteTransactionReq
	FundReply                = v1.FundReply
	FundReq                  = v1.FundReq
	GetUserBalanceListReply  = v1.GetUserBalanceListReply
	GetUserBalanceListReq    = v1.GetUserBalanceListReq
	GetUserBalanceReply      = v1.GetUserBalanceReply
	GetUserBalanceReq        = v1.GetUserBalanceReq
	TransactionReply         = v1.TransactionReply
	TransactionReq           = v1.TransactionReq
	TransferInProgressReply  = v1.TransferInProgressReply
	TransferInProgressReq    = v1.TransferInProgressReq
	TransferInReply          = v1.TransferInReply
	TransferInReq            = v1.TransferInReq
	TransferOutProgressReply = v1.TransferOutProgressReply
	TransferOutProgressReq   = v1.TransferOutProgressReq
	TransferOutReply         = v1.TransferOutReply
	TransferOutReq           = v1.TransferOutReq
	TransferProgressInfo     = v1.TransferProgressInfo
	UserBalanceInfo          = v1.UserBalanceInfo
	UserBalanceListReply     = v1.UserBalanceListReply
	UserBalanceListReq       = v1.UserBalanceListReq

	FundInnerService interface {
		// 获取单个用户余额[实时更新的余额]
		GetUserBalance(ctx context.Context, in *GetUserBalanceReq, opts ...grpc.CallOption) (*GetUserBalanceReply, error)
		// 批量获取用户余额[实时更新的余额]
		GetUserBalanceList(ctx context.Context, in *GetUserBalanceListReq, opts ...grpc.CallOption) (*GetUserBalanceListReply, error)
		// 处理交易（根据type字段处理不同类型）
		ProcessTransaction(ctx context.Context, in *TransactionReq, opts ...grpc.CallOption) (*TransactionReply, error)
		// 执行交易处理用于余额相关操作
		ExecuteTransaction(ctx context.Context, in *ExecuteTransactionReq, opts ...grpc.CallOption) (*ExecuteTransactionReply, error)
	}

	defaultFundInnerService struct {
		cli zrpc.Client
	}
)

func NewFundInnerService(cli zrpc.Client) FundInnerService {
	return &defaultFundInnerService{
		cli: cli,
	}
}

// 获取单个用户余额[实时更新的余额]
func (m *defaultFundInnerService) GetUserBalance(ctx context.Context, in *GetUserBalanceReq, opts ...grpc.CallOption) (*GetUserBalanceReply, error) {
	client := v1.NewFundInnerServiceClient(m.cli.Conn())
	return client.GetUserBalance(ctx, in, opts...)
}

// 批量获取用户余额[实时更新的余额]
func (m *defaultFundInnerService) GetUserBalanceList(ctx context.Context, in *GetUserBalanceListReq, opts ...grpc.CallOption) (*GetUserBalanceListReply, error) {
	client := v1.NewFundInnerServiceClient(m.cli.Conn())
	return client.GetUserBalanceList(ctx, in, opts...)
}

// 处理交易（根据type字段处理不同类型）
func (m *defaultFundInnerService) ProcessTransaction(ctx context.Context, in *TransactionReq, opts ...grpc.CallOption) (*TransactionReply, error) {
	client := v1.NewFundInnerServiceClient(m.cli.Conn())
	return client.ProcessTransaction(ctx, in, opts...)
}

// 执行交易处理用于余额相关操作
func (m *defaultFundInnerService) ExecuteTransaction(ctx context.Context, in *ExecuteTransactionReq, opts ...grpc.CallOption) (*ExecuteTransactionReply, error) {
	client := v1.NewFundInnerServiceClient(m.cli.Conn())
	return client.ExecuteTransaction(ctx, in, opts...)
}
