// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: platform/v1/platform.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGameLinkReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ThirdGameId     string                 `protobuf:"bytes,1,opt,name=third_game_id,json=thirdGameId,proto3" json:"third_game_id,omitempty"`             // 三方游戏id
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                              // 用户id
	CurrencyCode    string                 `protobuf:"bytes,3,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`            // 币种code
	ClientIp        string                 `protobuf:"bytes,4,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`                        // ip
	DeviceId        string                 `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                        // 设备号
	LanguageCode    string                 `protobuf:"bytes,6,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`            // 语言
	TransferBalance float64                `protobuf:"fixed64,7,opt,name=transfer_balance,json=transferBalance,proto3" json:"transfer_balance,omitempty"` // 转入金额
	PlatformId      int64                  `protobuf:"varint,8,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`                 // 厂商id
	ClientType      int64                  `protobuf:"varint,9,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"`                 // 设备类型 1 pc 2 手机 默认 2
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetGameLinkReq) Reset() {
	*x = GetGameLinkReq{}
	mi := &file_platform_v1_platform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameLinkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameLinkReq) ProtoMessage() {}

func (x *GetGameLinkReq) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_platform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameLinkReq.ProtoReflect.Descriptor instead.
func (*GetGameLinkReq) Descriptor() ([]byte, []int) {
	return file_platform_v1_platform_proto_rawDescGZIP(), []int{0}
}

func (x *GetGameLinkReq) GetThirdGameId() string {
	if x != nil {
		return x.ThirdGameId
	}
	return ""
}

func (x *GetGameLinkReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetGameLinkReq) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *GetGameLinkReq) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *GetGameLinkReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetGameLinkReq) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *GetGameLinkReq) GetTransferBalance() float64 {
	if x != nil {
		return x.TransferBalance
	}
	return 0
}

func (x *GetGameLinkReq) GetPlatformId() int64 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

func (x *GetGameLinkReq) GetClientType() int64 {
	if x != nil {
		return x.ClientType
	}
	return 0
}

type GetGameLinkResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameLinkResp) Reset() {
	*x = GetGameLinkResp{}
	mi := &file_platform_v1_platform_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameLinkResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameLinkResp) ProtoMessage() {}

func (x *GetGameLinkResp) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_platform_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameLinkResp.ProtoReflect.Descriptor instead.
func (*GetGameLinkResp) Descriptor() ([]byte, []int) {
	return file_platform_v1_platform_proto_rawDescGZIP(), []int{1}
}

func (x *GetGameLinkResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetUserBalanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBalanceReq) Reset() {
	*x = GetUserBalanceReq{}
	mi := &file_platform_v1_platform_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBalanceReq) ProtoMessage() {}

func (x *GetUserBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_platform_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBalanceReq.ProtoReflect.Descriptor instead.
func (*GetUserBalanceReq) Descriptor() ([]byte, []int) {
	return file_platform_v1_platform_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserBalanceReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserBalanceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`              // 用户id
	PlatformId    int64                  `protobuf:"varint,2,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"` // 厂商id
	Balance       float64                `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance,omitempty"`                        // 余额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBalanceResp) Reset() {
	*x = GetUserBalanceResp{}
	mi := &file_platform_v1_platform_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBalanceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBalanceResp) ProtoMessage() {}

func (x *GetUserBalanceResp) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_platform_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBalanceResp.ProtoReflect.Descriptor instead.
func (*GetUserBalanceResp) Descriptor() ([]byte, []int) {
	return file_platform_v1_platform_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserBalanceResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserBalanceResp) GetPlatformId() int64 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

func (x *GetUserBalanceResp) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type TransferReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                   // 用户id
	CurrencyCode  string                 `protobuf:"bytes,2,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"` // 币种code
	IsDeposit     bool                   `protobuf:"varint,4,opt,name=is_deposit,json=isDeposit,proto3" json:"is_deposit,omitempty"`         // 是否存款 true 存款 false 取款
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`                               // 金额(正数)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferReq) Reset() {
	*x = TransferReq{}
	mi := &file_platform_v1_platform_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferReq) ProtoMessage() {}

func (x *TransferReq) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_platform_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferReq.ProtoReflect.Descriptor instead.
func (*TransferReq) Descriptor() ([]byte, []int) {
	return file_platform_v1_platform_proto_rawDescGZIP(), []int{4}
}

func (x *TransferReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TransferReq) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *TransferReq) GetIsDeposit() bool {
	if x != nil {
		return x.IsDeposit
	}
	return false
}

func (x *TransferReq) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type TransferResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeNo       string                 `protobuf:"bytes,1,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"` // 交易订单号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResp) Reset() {
	*x = TransferResp{}
	mi := &file_platform_v1_platform_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResp) ProtoMessage() {}

func (x *TransferResp) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_platform_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResp.ProtoReflect.Descriptor instead.
func (*TransferResp) Descriptor() ([]byte, []int) {
	return file_platform_v1_platform_proto_rawDescGZIP(), []int{5}
}

func (x *TransferResp) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

type GetDemoGameLinkReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`                   // 游戏id
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                   // 用户id
	CurrencyCode  string                 `protobuf:"bytes,3,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"` // 币种code
	ClientType    int64                  `protobuf:"varint,4,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"`      // 设备类型 1 pc 2 手机 默认 2
	ClientIp      string                 `protobuf:"bytes,5,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`             // ip
	Language      string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`                             // 语言
	PlatformId    int64                  `protobuf:"varint,7,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`      // 厂商id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDemoGameLinkReq) Reset() {
	*x = GetDemoGameLinkReq{}
	mi := &file_platform_v1_platform_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDemoGameLinkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDemoGameLinkReq) ProtoMessage() {}

func (x *GetDemoGameLinkReq) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_platform_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDemoGameLinkReq.ProtoReflect.Descriptor instead.
func (*GetDemoGameLinkReq) Descriptor() ([]byte, []int) {
	return file_platform_v1_platform_proto_rawDescGZIP(), []int{6}
}

func (x *GetDemoGameLinkReq) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GetDemoGameLinkReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetDemoGameLinkReq) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *GetDemoGameLinkReq) GetClientType() int64 {
	if x != nil {
		return x.ClientType
	}
	return 0
}

func (x *GetDemoGameLinkReq) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *GetDemoGameLinkReq) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *GetDemoGameLinkReq) GetPlatformId() int64 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

type GameInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThirdGameId   string                 `protobuf:"bytes,1,opt,name=third_game_id,json=thirdGameId,proto3" json:"third_game_id,omitempty"` // 三方游戏ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                    // 游戏名称
	State         int64                  `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`                                 // 游戏状态
	BetState      int64                  `protobuf:"varint,4,opt,name=bet_state,json=betState,proto3" json:"bet_state,omitempty"`           // 游戏投注状态
	GameType      int64                  `protobuf:"varint,5,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`           // 游戏类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameInfo) Reset() {
	*x = GameInfo{}
	mi := &file_platform_v1_platform_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInfo) ProtoMessage() {}

func (x *GameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_platform_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInfo.ProtoReflect.Descriptor instead.
func (*GameInfo) Descriptor() ([]byte, []int) {
	return file_platform_v1_platform_proto_rawDescGZIP(), []int{7}
}

func (x *GameInfo) GetThirdGameId() string {
	if x != nil {
		return x.ThirdGameId
	}
	return ""
}

func (x *GameInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameInfo) GetState() int64 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *GameInfo) GetBetState() int64 {
	if x != nil {
		return x.BetState
	}
	return 0
}

func (x *GameInfo) GetGameType() int64 {
	if x != nil {
		return x.GameType
	}
	return 0
}

type GetGameListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameListReq) Reset() {
	*x = GetGameListReq{}
	mi := &file_platform_v1_platform_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameListReq) ProtoMessage() {}

func (x *GetGameListReq) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_platform_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameListReq.ProtoReflect.Descriptor instead.
func (*GetGameListReq) Descriptor() ([]byte, []int) {
	return file_platform_v1_platform_proto_rawDescGZIP(), []int{8}
}

type GetGameListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlatformId    int64                  `protobuf:"varint,1,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"` // 厂商id
	GameInfo      []*GameInfo            `protobuf:"bytes,2,rep,name=game_info,json=gameInfo,proto3" json:"game_info,omitempty"`        // 游戏列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameListResp) Reset() {
	*x = GetGameListResp{}
	mi := &file_platform_v1_platform_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameListResp) ProtoMessage() {}

func (x *GetGameListResp) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_platform_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameListResp.ProtoReflect.Descriptor instead.
func (*GetGameListResp) Descriptor() ([]byte, []int) {
	return file_platform_v1_platform_proto_rawDescGZIP(), []int{9}
}

func (x *GetGameListResp) GetPlatformId() int64 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

func (x *GetGameListResp) GetGameInfo() []*GameInfo {
	if x != nil {
		return x.GameInfo
	}
	return nil
}

var File_platform_v1_platform_proto protoreflect.FileDescriptor

const file_platform_v1_platform_proto_rawDesc = "" +
	"\n" +
	"\x1aplatform/v1/platform.proto\x12\vplatform.v1\"\xbe\x02\n" +
	"\x0eGetGameLinkReq\x12\"\n" +
	"\rthird_game_id\x18\x01 \x01(\tR\vthirdGameId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rcurrency_code\x18\x03 \x01(\tR\fcurrencyCode\x12\x1b\n" +
	"\tclient_ip\x18\x04 \x01(\tR\bclientIp\x12\x1b\n" +
	"\tdevice_id\x18\x05 \x01(\tR\bdeviceId\x12#\n" +
	"\rlanguage_code\x18\x06 \x01(\tR\flanguageCode\x12)\n" +
	"\x10transfer_balance\x18\a \x01(\x01R\x0ftransferBalance\x12\x1f\n" +
	"\vplatform_id\x18\b \x01(\x03R\n" +
	"platformId\x12\x1f\n" +
	"\vclient_type\x18\t \x01(\x03R\n" +
	"clientType\"#\n" +
	"\x0fGetGameLinkResp\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\",\n" +
	"\x11GetUserBalanceReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"h\n" +
	"\x12GetUserBalanceResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vplatform_id\x18\x02 \x01(\x03R\n" +
	"platformId\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x01R\abalance\"\x82\x01\n" +
	"\vTransferReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rcurrency_code\x18\x02 \x01(\tR\fcurrencyCode\x12\x1d\n" +
	"\n" +
	"is_deposit\x18\x04 \x01(\bR\tisDeposit\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\")\n" +
	"\fTransferResp\x12\x19\n" +
	"\btrade_no\x18\x01 \x01(\tR\atradeNo\"\xe6\x01\n" +
	"\x12GetDemoGameLinkReq\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rcurrency_code\x18\x03 \x01(\tR\fcurrencyCode\x12\x1f\n" +
	"\vclient_type\x18\x04 \x01(\x03R\n" +
	"clientType\x12\x1b\n" +
	"\tclient_ip\x18\x05 \x01(\tR\bclientIp\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\x12\x1f\n" +
	"\vplatform_id\x18\a \x01(\x03R\n" +
	"platformId\"\x92\x01\n" +
	"\bGameInfo\x12\"\n" +
	"\rthird_game_id\x18\x01 \x01(\tR\vthirdGameId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x03 \x01(\x03R\x05state\x12\x1b\n" +
	"\tbet_state\x18\x04 \x01(\x03R\bbetState\x12\x1b\n" +
	"\tgame_type\x18\x05 \x01(\x03R\bgameType\"\x10\n" +
	"\x0eGetGameListReq\"f\n" +
	"\x0fGetGameListResp\x12\x1f\n" +
	"\vplatform_id\x18\x01 \x01(\x03R\n" +
	"platformId\x122\n" +
	"\tgame_info\x18\x02 \x03(\v2\x15.platform.v1.GameInfoR\bgameInfo2\x90\x03\n" +
	"\x14PlatformInnerService\x12H\n" +
	"\vGetGameLink\x12\x1b.platform.v1.GetGameLinkReq\x1a\x1c.platform.v1.GetGameLinkResp\x12P\n" +
	"\x0fGetDemoGameLink\x12\x1f.platform.v1.GetDemoGameLinkReq\x1a\x1c.platform.v1.GetGameLinkResp\x12Q\n" +
	"\x0eGetUserBalance\x12\x1e.platform.v1.GetUserBalanceReq\x1a\x1f.platform.v1.GetUserBalanceResp\x12?\n" +
	"\bTransfer\x12\x18.platform.v1.TransferReq\x1a\x19.platform.v1.TransferResp\x12H\n" +
	"\vGetGameList\x12\x1b.platform.v1.GetGameListReq\x1a\x1c.platform.v1.GetGameListRespB8Z6github.com/og-game/game-proto/proto-gen-go/platform/v1b\x06proto3"

var (
	file_platform_v1_platform_proto_rawDescOnce sync.Once
	file_platform_v1_platform_proto_rawDescData []byte
)

func file_platform_v1_platform_proto_rawDescGZIP() []byte {
	file_platform_v1_platform_proto_rawDescOnce.Do(func() {
		file_platform_v1_platform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_v1_platform_proto_rawDesc), len(file_platform_v1_platform_proto_rawDesc)))
	})
	return file_platform_v1_platform_proto_rawDescData
}

var file_platform_v1_platform_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_platform_v1_platform_proto_goTypes = []any{
	(*GetGameLinkReq)(nil),     // 0: platform.v1.GetGameLinkReq
	(*GetGameLinkResp)(nil),    // 1: platform.v1.GetGameLinkResp
	(*GetUserBalanceReq)(nil),  // 2: platform.v1.GetUserBalanceReq
	(*GetUserBalanceResp)(nil), // 3: platform.v1.GetUserBalanceResp
	(*TransferReq)(nil),        // 4: platform.v1.TransferReq
	(*TransferResp)(nil),       // 5: platform.v1.TransferResp
	(*GetDemoGameLinkReq)(nil), // 6: platform.v1.GetDemoGameLinkReq
	(*GameInfo)(nil),           // 7: platform.v1.GameInfo
	(*GetGameListReq)(nil),     // 8: platform.v1.GetGameListReq
	(*GetGameListResp)(nil),    // 9: platform.v1.GetGameListResp
}
var file_platform_v1_platform_proto_depIdxs = []int32{
	7, // 0: platform.v1.GetGameListResp.game_info:type_name -> platform.v1.GameInfo
	0, // 1: platform.v1.PlatformInnerService.GetGameLink:input_type -> platform.v1.GetGameLinkReq
	6, // 2: platform.v1.PlatformInnerService.GetDemoGameLink:input_type -> platform.v1.GetDemoGameLinkReq
	2, // 3: platform.v1.PlatformInnerService.GetUserBalance:input_type -> platform.v1.GetUserBalanceReq
	4, // 4: platform.v1.PlatformInnerService.Transfer:input_type -> platform.v1.TransferReq
	8, // 5: platform.v1.PlatformInnerService.GetGameList:input_type -> platform.v1.GetGameListReq
	1, // 6: platform.v1.PlatformInnerService.GetGameLink:output_type -> platform.v1.GetGameLinkResp
	1, // 7: platform.v1.PlatformInnerService.GetDemoGameLink:output_type -> platform.v1.GetGameLinkResp
	3, // 8: platform.v1.PlatformInnerService.GetUserBalance:output_type -> platform.v1.GetUserBalanceResp
	5, // 9: platform.v1.PlatformInnerService.Transfer:output_type -> platform.v1.TransferResp
	9, // 10: platform.v1.PlatformInnerService.GetGameList:output_type -> platform.v1.GetGameListResp
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_platform_v1_platform_proto_init() }
func file_platform_v1_platform_proto_init() {
	if File_platform_v1_platform_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_v1_platform_proto_rawDesc), len(file_platform_v1_platform_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_platform_v1_platform_proto_goTypes,
		DependencyIndexes: file_platform_v1_platform_proto_depIdxs,
		MessageInfos:      file_platform_v1_platform_proto_msgTypes,
	}.Build()
	File_platform_v1_platform_proto = out.File
	file_platform_v1_platform_proto_goTypes = nil
	file_platform_v1_platform_proto_depIdxs = nil
}
