// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: workflow/v1/workflow.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkflowInnerService_Test_FullMethodName = "/temporal.v1.WorkflowInnerService/Test"
)

// WorkflowInnerServiceClient is the client API for WorkflowInnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkflowInnerServiceClient interface {
	Test(ctx context.Context, in *WorkflowReq, opts ...grpc.CallOption) (*WorkflowResp, error)
}

type workflowInnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkflowInnerServiceClient(cc grpc.ClientConnInterface) WorkflowInnerServiceClient {
	return &workflowInnerServiceClient{cc}
}

func (c *workflowInnerServiceClient) Test(ctx context.Context, in *WorkflowReq, opts ...grpc.CallOption) (*WorkflowResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowResp)
	err := c.cc.Invoke(ctx, WorkflowInnerService_Test_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowInnerServiceServer is the server API for WorkflowInnerService service.
// All implementations must embed UnimplementedWorkflowInnerServiceServer
// for forward compatibility.
type WorkflowInnerServiceServer interface {
	Test(context.Context, *WorkflowReq) (*WorkflowResp, error)
	mustEmbedUnimplementedWorkflowInnerServiceServer()
}

// UnimplementedWorkflowInnerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkflowInnerServiceServer struct{}

func (UnimplementedWorkflowInnerServiceServer) Test(context.Context, *WorkflowReq) (*WorkflowResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Test not implemented")
}
func (UnimplementedWorkflowInnerServiceServer) mustEmbedUnimplementedWorkflowInnerServiceServer() {}
func (UnimplementedWorkflowInnerServiceServer) testEmbeddedByValue()                              {}

// UnsafeWorkflowInnerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkflowInnerServiceServer will
// result in compilation errors.
type UnsafeWorkflowInnerServiceServer interface {
	mustEmbedUnimplementedWorkflowInnerServiceServer()
}

func RegisterWorkflowInnerServiceServer(s grpc.ServiceRegistrar, srv WorkflowInnerServiceServer) {
	// If the following call pancis, it indicates UnimplementedWorkflowInnerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkflowInnerService_ServiceDesc, srv)
}

func _WorkflowInnerService_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowInnerServiceServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowInnerService_Test_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowInnerServiceServer).Test(ctx, req.(*WorkflowReq))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkflowInnerService_ServiceDesc is the grpc.ServiceDesc for WorkflowInnerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkflowInnerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "temporal.v1.WorkflowInnerService",
	HandlerType: (*WorkflowInnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Test",
			Handler:    _WorkflowInnerService_Test_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workflow/v1/workflow.proto",
}
