// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: fund.proto

package gameapiservice

import (
	"context"

	"github.com/og-game/game-proto/proto-gen-go/fund/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateGameAddrReply = v1.CreateGameAddrReply
	CreateGameAddrReq   = v1.CreateGameAddrReq
	FundReply           = v1.FundReply
	FundReq             = v1.FundReq

	GameApiService interface {
		Test(ctx context.Context, in *CreateGameAddrReq, opts ...grpc.CallOption) (*CreateGameAddrReply, error)
	}

	defaultGameApiService struct {
		cli zrpc.Client
	}
)

func NewGameApiService(cli zrpc.Client) GameApiService {
	return &defaultGameApiService{
		cli: cli,
	}
}

func (m *defaultGameApiService) Test(ctx context.Context, in *CreateGameAddrReq, opts ...grpc.CallOption) (*CreateGameAddrReply, error) {
	client := v1.NewGameApiServiceClient(m.cli.Conn())
	return client.Test(ctx, in, opts...)
}
